### ISSUE TITLE
与VScode的markdown相互导入出的字体颜色及不相同问题。

### ISSUE THREAD

**Issue by StevenJokess** [toeverything/editoe#10]
复现步骤:

1. 由于VScode的所用theme![image](https://user-images.githubusercontent.com/71307974/108515021-919acb80-72ff-11eb-94a8-6e93ec6bde29.png)的白色字体
![image](https://user-images.githubusercontent.com/71307974/108514984-8778cd00-72ff-11eb-894f-c030a860e187.png)
，导致步骤二
2. ![image](https://user-images.githubusercontent.com/71307974/108514696-22bd7280-72ff-11eb-9fd6-fcd256ae2735.png)

3. 导出后多了很多加重号。
![image](https://user-images.githubusercontent.com/71307974/108515085-a8412280-72ff-11eb-8562-1505e7be3029.png)

**Comment by L-Sun** [comment]
剪切板内容是由所在软件控制(如vscode)，因此剪切板中的格式千奇百怪。目前暂无计划适配VScode内容的粘贴导入功能。

**Comment by L-Sun** [comment]
剪切板内容是由所在软件控制(如vscode)，因此剪切板中的格式千奇百怪。目前暂无计划适配VScode内容的粘贴导入功能。
