### ISSUE TITLE
代替种子用户上传的bug反馈（二）：“对导出pdf排版不太满意”

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#102]
原文：“标题太小且符号有问题、侧边栏遮掩、代码块没有背景颜色、导出文字只有一部分。希望有word，导出markdown没反应”

**Comment by L-Sun** [comment]
1. 导出pdf功能会暂时下线，其因是这个功能不够完善。
2. 导出markdown会在后台进行转换处理，但目前没有交互元素来传达 **正在转换** 这个信息，需要改进。

**Comment by unknownuser1-1** [comment]
> 
> 
>     1. 导出pdf功能会暂时下线，其因是这个功能不够完善。
> 
>     2. 导出markdown会在后台进行转换处理，但目前没有交互元素来传达 **正在转换** 这个信息，需要改进。

这个要交给UIUX设计一下么，还是研发这边直接改得了，其实就是弹一个框出来显示一下正在转换就行。

**Comment by chenyang9725** [comment]
一般有设计会好一点，不然研发自己搞，可能之后还有改。
不过研发要搞的话，可以用material-ui组件 https://material-ui.com/zh/components/progress/#progress

**Comment by L-Sun** [comment]
> 导出markdown没反应

已经加入进度条来提示，_正在导出_

**Comment by L-Sun** [comment]
现在已经又pdf导出功能
