### ISSUE TITLE
登录界面建议

### ISSUE THREAD

**Issue by StevenJokess** [toeverything/editoe#11]
![image](https://user-images.githubusercontent.com/71307974/108516053-ba6f9080-7300-11eb-900e-ef0a176bdc8e.png)

**Comment by L-Sun** [comment]
请提供以下信息
1. 浏览器
2. 系统

PS: 请在提issue时，使用模板，并填写相应的信息，这有助于我们排查问题~

**Comment by StevenJokess** [comment]
![image](https://user-images.githubusercontent.com/71307974/108839458-0fb4e600-7610-11eb-8c48-90910874555d.png)
我觉得类似这种更好。
