### ISSUE TITLE
代码块空格在特殊情景下会转为回车

### ISSUE THREAD

**Issue by HeJiachen-PM** [toeverything/editoe#113]
- 操作系统版本: macOS
- 浏览器版本: chrome

复现步骤:

1.经PM测试似乎无法准确复现，但用户上传了录屏视频：
https://user-images.githubusercontent.com/79301703/110236919-dcf5e080-7f73-11eb-9ffb-c34fbbb4a265.mp4
2.用户代码：# 添加头文件参数
outdir="./demo/reduced_data/" 
sfiles=glob.glob("./demo/raw_data/d*UW32R*.fit")  # science frames 
sfiles.sort()  # in alphabetic order

for i,ifile in enumerate(sfiles):
    print("reducing (debias, flat-fielding, and flipping) :", i+1, len(sfiles), ifile) 
    indir,infile=os.path.split(ifile)
    rootname,_=os.path.splitext(infile)
    # 将新文件首字母由d改成p，防止覆盖
    outfile=os.path.join(outdir,"p"+rootname[1:]+'.fit') 
    head=fits.getheader(ifile,output_verifystr="silentfix")  # 读出头文件
    # 科学图像剪裁起点
    col_origin=head['CRVAL1']
    row_origin=head['CRVAL2'] 
 subflat=domeflat[row_origin:row_origin+512,col_origin:col_origin+512]    # 剪裁平场
 subbias=superbias[row_origin:row_origin+512,col_origin:col_origin+512]   # 剪裁本底

    # 只是一个剪裁后的本底和平场的例子
    if i==0:
 fits.writeto('./demo/reduced_data/subflat.fit',subflat.astype('float32'),overwrite=True)
 fits.writeto('./demo/reduced_data/subbias.fit',subbias.astype('float32'),overwrite=True)   # 注意路径
    data=fits.getdata(ifile)   # 读出科学数据
    # 减平场，除本底
    data=(data-subbias)/subflat 
    # 如果要做位置定标，需要设定初始的WCS参数参考点

    # 添加头文件参数
    head['epoch']=2000.0   # 历元
    head['CRVAL1']=ra      # 参考点赤经
    head['CRVAL2']=dec     # 参考点赤纬
    head['CRPIX1']=head['NAXIS1']/2.0      # 轴1参考点像素坐标，为总像素数NAXIS1（生成头文件时自带）的一半
    head['CRPIX2']=head['NAXIS2']/2.0      # 轴2参考点像素坐标，为总像素数NAXIS2（生成头文件时自带）的一半
    head['CDELT1']=-pixscale/3600.0        # 轴1像元尺度，单位为度，注意负号，因为左边是东
    head['CDELT2']=pixscale/3600.0         # 轴2像元尺度，单位为度，正值
    head['CTYPE1']='RA---TAN'              # 投影类型
    head['CTYPE2']='DEC--TAN'              # 投影类型
    head['GAIN']=(gain,'GAIN in e-/ADU')   # 增益，e-/ADU
    head['RDNOISE']=(rdnoise,'readout noise in electron') # 读出噪声，e-
    print("writing to "+outfile)

    # 翻转图像使北朝上并写入fits
 fits.writeto(outfile,np.flipud(data),header=head,overwrite=True,output_verify="silentfix")
    # silentfix可以自动修改不规范的头文件参数，但是不返回过多信息

**Comment by L-Sun** [comment]
### 问题复现：
1. 唤起代码块
2. 在代码块中第一行输入足够多的字母，触发自动换行
3. 在行首输入空格

### 预期效果：
空格被加入

### 实际效果：
整行被换行
