### ISSUE TITLE
立即开始后，无导出栏

### ISSUE THREAD

**Issue by StevenJokess** [toeverything/editoe#12]
- 操作系统版本: 
- 浏览器版本: 

复现步骤:

1. 官网这里点进去
![image](https://user-images.githubusercontent.com/71307974/108518603-b6913d80-7303-11eb-9fa9-12bcc024d0d1.png)

2. 会发现没有右侧的“导出”等的栏
![image](https://user-images.githubusercontent.com/71307974/108519342-7f6f5c00-7304-11eb-9306-30c84648ff74.png)

对比
![image](https://user-images.githubusercontent.com/71307974/108519265-71b9d680-7304-11eb-90d9-325029ea63c0.png)

**Comment by L-Sun** [comment]
此页面为编辑展示，图中的功能在用户自己的文章中才会启用。

> ![image](https://user-images.githubusercontent.com/71307974/108519265-71b9d680-7304-11eb-90d9-325029ea63c0.png)

**Comment by StevenJokess** [comment]
@L-Sun 老哥我知道是编辑展示，也知道那个是出现在，所以不把功能展示全？fix 吗？

**Comment by L-Sun** [comment]
> @L-Sun 老哥我知道是编辑展示，也知道那个是出现在，所以不把功能展示全？fix 吗？

这些功能属于“用户”相关功能，需要登录才能开启，而展示页面的文章不属于任何一个用户、故不会开启这些功能。
