### ISSUE TITLE
选中多行文字后使用列表功能

### ISSUE THREAD

**Issue by YaweiWangTOE** [toeverything/editoe#123]
### 功能描述

![image](https://user-images.githubusercontent.com/79351864/110598124-5da71d80-81bc-11eb-8f92-f7d02271dc8d.png)
只会在第一行出现列表（默认将选中的文字全部作为一个项目），建议能根据行数自动生成多项
<hr>

如果你觉得这个功能很实用、很酷，请为此 Featrue 点个:+1:

**Comment by L-Sun** [comment]
现在可以生成多个序号了
