### ISSUE TITLE
左侧导航区被遮挡，无法点击

### ISSUE THREAD

**Issue by chenyang9725** [toeverything/editoe#126]
### 问题描述

![image](https://user-images.githubusercontent.com/79300514/110733386-cea01100-8260-11eb-9b97-bd561358273b.png)
在https://canary.editoe.com/editor  点击左侧导航栏，无法点击，似乎被遮挡了

### 预期效果:

可以点击
### 实际效果:
无法点击

**Comment by L-Sun** [comment]
Fixed
