### ISSUE TITLE
移动文件夹问题

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#129]
1. 现在在移动文件夹时可以选择该文件夹本身为目标，而移动后该文件夹将连带其中的文档一起消失（不知道后台是否还在？），见视频https://www.awesomescreenshot.com/video/3219749?key=35c966e1c48310d400411b59fe5bfee2。
2.可能需要调整显示效果，我这里不显示最顶部文档名：
![图片](https://user-images.githubusercontent.com/79503478/110734438-ccd74d00-8262-11eb-8b72-ca5f21ada775.png)

**Comment by unknownuser1-1** [comment]
虽然刚才说没修，但我这好像没这问题了

**Comment by chenyang9725** [comment]
fixed

**Comment by unknownuser1-1** [comment]
问题1还存在，上线后麻烦再关一下 @chenyang9725
