### ISSUE TITLE
待办列表勾选的颜色样式和sidebar复选保持一致

### ISSUE THREAD

**Issue by chenyang9725** [toeverything/editoe#131]
### 功能描述

待办列表勾选的颜色样式和sidebar复选保持一致
<hr>
![image](https://user-images.githubusercontent.com/79300514/110750081-eeddc900-827c-11eb-8b19-a4b42ea31594.png)

![image](https://user-images.githubusercontent.com/79300514/110749963-c1911b00-827c-11eb-8dba-2d23424699af.png)

颜色使用主题色

**Comment by fangyuan-zheng** [comment]
已改
