### ISSUE TITLE
表格内文字选择

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#137]
现在表格选择文本不会出现正常的蓝色选择条，而是什么都不显示，无论是全选、部分选择都不显示（但实际是能选中的），完全无法看出到底选择了哪些内容，甚至于没有测试之前我都不知道选了没选。
![图片](https://user-images.githubusercontent.com/79503478/110750724-df12b480-827d-11eb-8a04-e0f368db622d.png)

**Comment by L-Sun** [comment]
文字选择的背景色和当前被选中的表格背景色相同

**Comment by L-Sun** [comment]
@fangyuan-zheng 对表格里边选中的文字，背景色可以调整一下，以便于区分

**Comment by L-Sun** [comment]
已修复
