### ISSUE TITLE
新建文档的按钮位置可以调整吗？目前不够显眼

### ISSUE THREAD

**Issue by qierchen-toe** [toeverything/editoe#138]
### 功能描述

可以参照豆瓣，pendo的新建笔记，将新建和list按钮分开放置在不同角落

<hr>

如果你觉得这个功能很实用、很酷，请为此 Featrue 点个:+1:

**Comment by unknownuser1-1** [comment]
其他网站效果截个图吧，我觉得其实现在还挺明显的。

**Comment by qierchen-toe** [comment]
也不是显眼问题啦，就和其他功能键放在一起看起来差不多，新建应该是个关键功能，以下case都单独拎出来放，或做了特殊颜色和大小 ​[image] ​​[image] ​​[image] ​

**Comment by unknownuser1-1** [comment]
> 
> 也不是显眼问题啦，就和其他功能键放在一起看起来差不多，新建应该是个关键功能，以下case都单独拎出来放，或做了特殊颜色和大小 ​[image] ​​[image] ​​[image] ​

截图没传上来，现在这样不是一眼就能看出是新建么：
![图片](https://user-images.githubusercontent.com/79503478/110761321-8f86b580-828a-11eb-96b6-6cca748375d1.png)

**Comment by unknownuser1-1** [comment]
依讨论，挪动位置至上图的左侧
