### ISSUE TITLE
新建文档点开啥都没了（未编辑过）现存文档打开也没了

### ISSUE THREAD

**Issue by qierchen-toe** [toeverything/editoe#139]
### 问题描述

TypeError: Cannot read property 'split' of undefined
    at yn (18.3a996f953996abbe8c26.js:1)
    at pn (18.3a996f953996abbe8c26.js:1)
    at n.callback (18.3a996f953996abbe8c26.js:1)
    at n.value (18.3a996f953996abbe8c26.js:1)
    at 18.3a996f953996abbe8c26.js:1
    at Array.map (<anonymous>)
    at 18.3a996f953996abbe8c26.js:1
    at B (18.3a996f953996abbe8c26.js:1)
    at e.value (18.3a996f953996abbe8c26.js:1)
    at e.value (18.3a996f953996abbe8c26.js:1) {phase: "initialization", willEditorRestart: false}
onError @ 18.3a996f953996abbe8c26.js:1
(anonymous) @ 18.3a996f953996abbe8c26.js:1
Promise.catch (async)
_initializeEditor @ 18.3a996f953996abbe8c26.js:1
componentDidMount @ 18.3a996f953996abbe8c26.js:1
hu @ framework.36e5d30ecc6dc4b81c51.js:1
Li @ framework.36e5d30ecc6dc4b81c51.js:1
t.unstable_runWithPriority @ framework.36e5d30ecc6dc4b81c51.js:1
Hl @ framework.36e5d30ecc6dc4b81c51.js:1
Ti @ framework.36e5d30ecc6dc4b81c51.js:1
gi @ framework.36e5d30ecc6dc4b81c51.js:1
(anonymous) @ framework.36e5d30ecc6dc4b81c51.js:1
t.unstable_runWithPriority @ framework.36e5d30ecc6dc4b81c51.js:1
Hl @ framework.36e5d30ecc6dc4b81c51.js:1
Ql @ framework.36e5d30ecc6dc4b81c51.js:1
$l @ framework.36e5d30ecc6dc4b81c51.js:1
fi @ framework.36e5d30ecc6dc4b81c51.js:1
No @ framework.36e5d30ecc6dc4b81c51.js:1
e @ framework.36e5d30ecc6dc4b81c51.js:1
(anonymous) @ fa3a5c69c7737507ad3c502e571c9adffd268a52.760780f5ab9818f065f1.js:1
value @ fa3a5c69c7737507ad3c502e571c9adffd268a52.760780f5ab9818f065f1.js:1
(anonymous) @ fa3a5c69c7737507ad3c502e571c9adffd268a52.760780f5ab9818f065f1.js:1
Promise.then (async)
value @ fa3a5c69c7737507ad3c502e571c9adffd268a52.760780f5ab9818f065f1.js:1
e @ fa3a5c69c7737507ad3c502e571c9adffd268a52.760780f5ab9818f065f1.js:1
a @ fa3a5c69c7737507ad3c502e571c9adffd268a52.760780f5ab9818f065f1.js:1
LoadableComponent @ fa3a5c69c7737507ad3c502e571c9adffd268a52.760780f5ab9818f065f1.js:1
ro @ framework.36e5d30ecc6dc4b81c51.js:1
Do @ framework.36e5d30ecc6dc4b81c51.js:1
$u @ framework.36e5d30ecc6dc4b81c51.js:1
Pi @ framework.36e5d30ecc6dc4b81c51.js:1
xi @ framework.36e5d30ecc6dc4b81c51.js:1
_i @ framework.36e5d30ecc6dc4b81c51.js:1
gi @ framework.36e5d30ecc6dc4b81c51.js:1
(anonymous) @ framework.36e5d30ecc6dc4b81c51.js:1
t.unstable_runWithPriority @ framework.36e5d30ecc6dc4b81c51.js:1
Hl @ framework.36e5d30ecc6dc4b81c51.js:1
Ql @ framework.36e5d30ecc6dc4b81c51.js:1
$l @ framework.36e5d30ecc6dc4b81c51.js:1
fi @ framework.36e5d30ecc6dc4b81c51.js:1
No @ framework.36e5d30ecc6dc4b81c51.js:1
(anonymous) @ 51315ffd8bf955b386d54f997f26d452ad0af74a.4d6e9944716c1408e55a.js:1
(anonymous) @ 51315ffd8bf955b386d54f997f26d452ad0af74a.4d6e9944716c1408e55a.js:1
(anonymous) @ 51315ffd8bf955b386d54f997f26d452ad0af74a.4d6e9944716c1408e55a.js:1
(anonymous) @ 51315ffd8bf955b386d54f997f26d452ad0af74a.4d6e9944716c1408e55a.js:1
a @ 51315ffd8bf955b386d54f997f26d452ad0af74a.4d6e9944716c1408e55a.js:1
Promise.then (async)
u @ 51315ffd8bf955b386d54f997f26d452ad0af74a.4d6e9944716c1408e55a.js:1
(anonymous) @ 51315ffd8bf955b386d54f997f26d452ad0af74a.4d6e9944716c1408e55a.js:1
p @ 51315ffd8bf955b386d54f997f26d452ad0af74a.4d6e9944716c1408e55a.js:1
(anonymous) @ 51315ffd8bf955b386d54f997f26d452ad0af74a.4d6e9944716c1408e55a.js:1
n @ 51315ffd8bf955b386d54f997f26d452ad0af74a.4d6e9944716c1408e55a.js:1
(anonymous) @ 51315ffd8bf955b386d54f997f26d452ad0af74a.4d6e9944716c1408e55a.js:1
hu @ framework.36e5d30ecc6dc4b81c51.js:1
Li @ framework.36e5d30ecc6dc4b81c51.js:1
t.unstable_runWithPriority @ framework.36e5d30ecc6dc4b81c51.js:1
Hl @ framework.36e5d30ecc6dc4b81c51.js:1
Ti @ framework.36e5d30ecc6dc4b81c51.js:1
gi @ framework.36e5d30ecc6dc4b81c51.js:1
(anonymous) @ framework.36e5d30ecc6dc4b81c51.js:1
t.unstable_runWithPriority @ framework.36e5d30ecc6dc4b81c51.js:1
Hl @ framework.36e5d30ecc6dc4b81c51.js:1
Ql @ framework.36e5d30ecc6dc4b81c51.js:1
$l @ framework.36e5d30ecc6dc4b81c51.js:1
fi @ framework.36e5d30ecc6dc4b81c51.js:1
Gi @ framework.36e5d30ecc6dc4b81c51.js:1
rs @ framework.36e5d30ecc6dc4b81c51.js:1
t.render @ framework.36e5d30ecc6dc4b81c51.js:1
me @ main-2949a180ad3630a0ab74.js:1
(anonymous) @ main-2949a180ad3630a0ab74.js:1
s @ 5ceedcd7d4e0a63467c63e446ba0a1bac858e423.bb30e81ac622ce54570a.js:1
(anonymous) @ 5ceedcd7d4e0a63467c63e446ba0a1bac858e423.bb30e81ac622ce54570a.js:1
(anonymous) @ 5ceedcd7d4e0a63467c63e446ba0a1bac858e423.bb30e81ac622ce54570a.js:1
r @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
s @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
(anonymous) @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
(anonymous) @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
ae @ main-2949a180ad3630a0ab74.js:1
subscription @ main-2949a180ad3630a0ab74.js:1
value @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
value @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
(anonymous) @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
s @ 5ceedcd7d4e0a63467c63e446ba0a1bac858e423.bb30e81ac622ce54570a.js:1
(anonymous) @ 5ceedcd7d4e0a63467c63e446ba0a1bac858e423.bb30e81ac622ce54570a.js:1
(anonymous) @ 5ceedcd7d4e0a63467c63e446ba0a1bac858e423.bb30e81ac622ce54570a.js:1
r @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
s @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
Promise.then (async)
r @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
s @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
Promise.then (async)
r @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
s @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
Promise.then (async)
r @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
s @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
(anonymous) @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
(anonymous) @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
(anonymous) @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
value @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
value @ main-2949a180ad3630a0ab74.js:1
hu @ framework.36e5d30ecc6dc4b81c51.js:1
Li @ framework.36e5d30ecc6dc4b81c51.js:1
t.unstable_runWithPriority @ framework.36e5d30ecc6dc4b81c51.js:1
Hl @ framework.36e5d30ecc6dc4b81c51.js:1
Ti @ framework.36e5d30ecc6dc4b81c51.js:1
gi @ framework.36e5d30ecc6dc4b81c51.js:1
fi @ framework.36e5d30ecc6dc4b81c51.js:1
Gi @ framework.36e5d30ecc6dc4b81c51.js:1
(anonymous) @ framework.36e5d30ecc6dc4b81c51.js:1
yi @ framework.36e5d30ecc6dc4b81c51.js:1
rs @ framework.36e5d30ecc6dc4b81c51.js:1
t.hydrate @ framework.36e5d30ecc6dc4b81c51.js:1
me @ main-2949a180ad3630a0ab74.js:1
(anonymous) @ main-2949a180ad3630a0ab74.js:1
s @ 5ceedcd7d4e0a63467c63e446ba0a1bac858e423.bb30e81ac622ce54570a.js:1
(anonymous) @ 5ceedcd7d4e0a63467c63e446ba0a1bac858e423.bb30e81ac622ce54570a.js:1
(anonymous) @ 5ceedcd7d4e0a63467c63e446ba0a1bac858e423.bb30e81ac622ce54570a.js:1
r @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
s @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
(anonymous) @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
(anonymous) @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
ie @ main-2949a180ad3630a0ab74.js:1
ae @ main-2949a180ad3630a0ab74.js:1
(anonymous) @ main-2949a180ad3630a0ab74.js:1
s @ 5ceedcd7d4e0a63467c63e446ba0a1bac858e423.bb30e81ac622ce54570a.js:1
(anonymous) @ 5ceedcd7d4e0a63467c63e446ba0a1bac858e423.bb30e81ac622ce54570a.js:1
(anonymous) @ 5ceedcd7d4e0a63467c63e446ba0a1bac858e423.bb30e81ac622ce54570a.js:1
r @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
s @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
Promise.then (async)
r @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
s @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
Promise.then (async)
r @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
s @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
Promise.then (async)
r @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
s @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
(anonymous) @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
(anonymous) @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
(anonymous) @ main-2949a180ad3630a0ab74.js:1
BMP1 @ main-2949a180ad3630a0ab74.js:1
l @ webpack-bec3da859aac99987f90.js:1
n @ webpack-bec3da859aac99987f90.js:1
t @ webpack-bec3da859aac99987f90.js:1
(anonymous) @ c066abe777a065d3277cb06f668c052039ca237a.d02248c0ffaf3ba782cb.js:1
Show 76 more frames
### 运行环境
- 操作系统版本: 
- 浏览器版本:

## 复现步骤:

1. 
2.

**Comment by L-Sun** [comment]
能配个图，说明一下怎么弄出来的吗？

**Comment by L-Sun** [comment]
已修复
