### ISSUE TITLE
关于公式自动换行，较严重bug

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#141]
输入公式，将其挪入下一行，之后无法用鼠标在公式前端插入光标，不过此时尚可以使用移动键→挪动光标至该位置，从而实现移动公式向前一行挪动，但是不太方便。

**更严重的问题**：如一开始公式就是插在正文中的，此时刷新页面，公式会自动换行（如图），且此时无论是鼠标还是移动键，都无法移动公式，就算复制公式至前一行，仍会自动换行。

为什么需要紧急修复：在需要文内插入公式的文档中，会完全破坏排版，且重新输入公式再刷新页面，问题会重现，导致文档完全无法使用。

测试文档：https://canary.editoe.com/docs/doc746a8b23f8dcc912
![图片](https://user-images.githubusercontent.com/79503478/110895382-9833c600-8334-11eb-8da8-f02f051679f3.png)

**Comment by L-Sun** [comment]
已修复
