### ISSUE TITLE
块引用方案

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#142]
之前已达成共识中文不用斜体，而是换用字体，如楷体，但至今尚未实现。如果技术上有困难或者工期过紧，能否临时取消块引用自带的斜体格式。目前创作者以中文用户居多，块引用中文斜体视觉效果不太行。

**Comment by unknownuser1-1** [comment]
@L-Sun 我的意思是能不能把块引用的斜体删掉，斜体/字体转换以后再做。而且实际上块引用即使是英文文献也经常是不斜体的，因为缩进本身已经足够起到强调作用，这并不是一个强制学术格式，应该还是让用户可以自由选择斜体与否。

**Comment by L-Sun** [comment]
Fixed
