### ISSUE TITLE
Keyboard Accessible：Ctrl + F 唤出查找替换插件

### ISSUE THREAD

**Issue by niudai** [toeverything/editoe#143]
### 功能描述

Ctrl + F 是用户最习惯的一个快捷键，我在飞书里按 Ctrl + F 的确可以唤出查找替换功能：
![image](https://user-images.githubusercontent.com/44165182/110926687-aba85680-835f-11eb-90c3-29fe1addfbbc.png)

<hr>

如果你觉得这个功能很实用、很酷，请为此 Featrue 点个:+1:

**Comment by L-Sun** [comment]
已添加
