### ISSUE TITLE
[BUG]: 新建参考文献页面闪退

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#145]
**新建文献文件夹之后**，点击新建参考文献，切换到其他窗口，返回后参考文献窗口**必然会消失。**

即使不是新建的文件夹，参考文献窗口也有一定概率在切换窗口后消失，但是出现概率较低，难以复现。

**Comment by L-Sun** [comment]
测试了，没有，能否补个视频

**Comment by unknownuser1-1** [comment]
经讨论还是并入0.5

**Comment by L-Sun** [comment]
已修复
