### ISSUE TITLE
[BUG]: 插入的表格无法完全删除

### ISSUE THREAD

**Issue by fangyuan-zheng** [toeverything/editoe#146]
### 问题描述

一旦插入表格，就无法删除表格。
![image](https://user-images.githubusercontent.com/79300990/111124875-f61e1300-85ab-11eb-8564-67ac175dc7c0.png)

表格删除到最后一格就无法删除了。
![image](https://user-images.githubusercontent.com/79300990/111124890-fa4a3080-85ab-11eb-9e10-6cc453213d30.png)

### 运行环境
- 操作系统版本: Chrome
- 浏览器版本:  89.0.4389.82

## 复现步骤:

1. 插入表格。
2. 点击上方图标，选择删除本行，知道删除最后一个放个，无法删除。

### 预期效果:

表格插入之后能够删除

**Comment by L-Sun** [comment]
现在点击表格时，左上角会出现一个按钮来选中整个表格，此时可以被删除
