### ISSUE TITLE
[Enhancement]: 文件名有空格问题

### ISSUE THREAD

**Issue by fangyuan-zheng** [toeverything/editoe#147]
## 问题描述

创建文件夹如果误输入空格，空格也会作为名字的一部分以 &nbsp; 显示
![image](https://user-images.githubusercontent.com/79300990/111125729-e8b55880-85ac-11eb-9622-7a91da67e199.png)
![image](https://user-images.githubusercontent.com/79300990/111125754-ec48df80-85ac-11eb-9291-ca2830bc857c.png)

## 预期效果

用户可能在输入名字的时候不小心输入空格，这些空格应该被清除

<hr>

如果你觉得这个改进很实用、很酷，请为此 Enhancement 点个:+1:

**Comment by L-Sun** [comment]
创建文件时，应该需要有个文件名格式加以限制，同时在string和html转换时，要考虑到空格这些会被转义的字符
