### ISSUE TITLE
[BUG]:注册未输入邀请码，第二次输入显示注册失败 

### ISSUE THREAD

**Issue by haozhangpatrick** [toeverything/editoe#149]
### 问题描述

在注册界面需要输入手机号码，验证码和邀请码。第一次输入手机号码和正确验证码后点击注册显示登录失败；第二次补充正确邀请码后显示注册失败。

### 运行环境
- 操作系统版本: macOS Mojave 10.14
- 浏览器版本:Chrome Version 88.0.4324.192 (Official Build) (x86_64)

## 复现步骤:

1. 输入手机号码和正确验证码，点击注册
2. 显示登录失败
3. 停留在原界面，补充正确邀请码
4. 显示**注册失败**

### 预期效果:

1. 输入手机号码和正确验证码，点击注册
2. 显示登录失败
3. 停留在原界面，补充正确邀请码
4. 显示**注册成功**

**Comment by L-Sun** [comment]
@wangyu654 邀请码上线之后，没有注册过的手机是不是应该获取不了验证码

**Comment by wangyu654** [comment]
@L-Sun  是的，等下改一下

**Comment by HeJiachen-PM** [comment]
已修复
