### ISSUE TITLE
/editor 页面告知用户该页面仅作演示

### ISSUE THREAD

**Issue by niudai** [toeverything/editoe#15]
- 操作系统版本: 
- 浏览器版本: 

复现步骤:

`/editor` 页面是做演示用的，很多功能没有放在这个页面上，但是用户常常觉得这是它自己的一篇文档，他会觉得 “为什么没有自动保存”，“ @ 不起作用”，会让用户很疑惑。

可以看下 VSCode 是怎么做的：

![image](https://user-images.githubusercontent.com/44165182/108585358-25fa4200-7383-11eb-99bc-a47e93ae11c4.png)

我的想法是，用户在首页点击 “立即开始” 的时候，如果用户没有登录，就跳转至现在的 /editor 展示性页面，但要增加 本地保存，然后在演示页面的 第一段用红线表明本页的 limitation，比如：

![image](https://user-images.githubusercontent.com/44165182/108585504-cf413800-7383-11eb-9506-81316e0f15bc.png)

如果用户已经登陆，点击 “立即开始” 的时候，应该跳转至它的 我的文档 页面，而不是 /editor 的展示页面。

我的文档 应该有一个 最近使用的文档 的部分，这个放在另一个 issue 里说吧。

**Comment by chenyang9725** [comment]
completed
