### ISSUE TITLE
[Enhancement]: 标题格式、标题等级按钮占空间太大

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#151]
**按钮和菜单**本身占空间都有点多，没必要占这么多空间，够用就行，也能给其他按钮挪出空间来。
![图片](https://user-images.githubusercontent.com/79503478/111271792-a5baba00-866c-11eb-9ee2-5908d8fa20de.png)

**Comment by L-Sun** [comment]
@miuer970612-24 设计看看
