### ISSUE TITLE
[BUG]: 较大表格会影响编辑界面大小

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#157]
### 问题描述
主要问题：一些较大的表格会影响界面大小。
附带的小问题：表格输入**数字或字母**（汉字可以正常换行）后也会使得编辑框超出正常编辑界面。

### 运行环境
- 操作系统版本: win10
- 浏览器版本:edge

## 复现步骤:

- 主要问题：复制一个较长的表格，如https://canary.editoe.com/docs/doc9b50f531e99b627a#docb84d998ddb81c206  这时候所有列全部为标题列，但此时可以正常显示，但是一旦将前三列之后的标题列取消之后，整个编辑界面就会扩大许多。
 **注**：如果是故意设计较大表格可以扩大编辑界面，倒也不是不可以，但一来它会影响左右侧菜单栏的显示效果，二来什么明明复制之后可以正常显示，更改之后才会扩大？

- 附带的小问题：在表格中，输入**数字或字母**（汉字可以正常换行）后使得编辑框超出编辑界面，见图。

![图片](https://user-images.githubusercontent.com/79503478/111412203-f5ee5680-8716-11eb-855f-44df4e4853dd.png)

### 预期效果:

![图片](https://user-images.githubusercontent.com/79503478/111412475-71500800-8717-11eb-9691-bcbf00f46d69.png)

### 实际效果:
![图片](https://user-images.githubusercontent.com/79503478/111412445-672e0980-8717-11eb-94c9-5d374e39dc17.png)

**Comment by L-Sun** [comment]
已修复，如有问题请 reopen 此 issue
