### ISSUE TITLE
[Enhancement]: 初始界面点击头像后整体页面的位移问题

### ISSUE THREAD

**Issue by Tian-Zhang** [toeverything/editoe#158]
## 问题描述

在初始界面点击右上角的头像后，整体页面会出现轻微位移

## 预期效果

不位移即可
<hr>

如果你觉得这个改进很实用、很酷，请为此 Enhancement 点个:+1:

**Comment by L-Sun** [comment]
这个问题应该没有了

**Comment by L-Sun** [comment]
这个问题应该没有了

**Comment by Tian-Zhang** [comment]
我看了一下，依然存在位移的情况，不过比之前改善很多了，但看着还是有些别扭

**Comment by L-Sun** [comment]
@Tian-Zhang 能否录个小视频看看
