### ISSUE TITLE
[Enhancement]: 编辑界面，左上角的放大镜功能的悬浮气泡提示跑到了界面之外

### ISSUE THREAD

**Issue by Tian-Zhang** [toeverything/editoe#159]
## 问题描述

编辑界面，左上角的放大镜功能的悬浮气泡提示跑到了界面之外
## 预期效果

能看到完整的气泡提示
<hr>

如果你觉得这个改进很实用、很酷，请为此 Enhancement 点个:+1:

**Comment by L-Sun** [comment]
已修复
