### ISSUE TITLE
我的文档，增加最近使用的文档 section

### ISSUE THREAD

**Issue by niudai** [toeverything/editoe#16]
![image](https://user-images.githubusercontent.com/44165182/108585787-4e833b80-7385-11eb-8d77-fa01b950a4c0.png)

我们可以在我的文档页面增加一个最近使用的文档的 section：

![image](https://user-images.githubusercontent.com/44165182/108585820-87bbab80-7385-11eb-91b6-33d63fa91130.png)

推荐最近的文档在上方，可以只显示三个，再加个更多按钮，最多显示六个。

**Comment by YaweiWangTOE** [comment]
也可以考虑把常用文档设置为文档打开时的默认页面，入口放在左侧

**Comment by L-Sun** [comment]
@niudai 如果将文档文献集成在SideBar去，是否还需要做这个页面的功能？

**Comment by YaweiWangTOE** [comment]
我个人会喜欢有一个页面来管理文档文献，可以做个小调研看看

**Comment by L-Sun** [comment]
> 我个人会喜欢有一个页面来管理文档文献，可以做个小调研看看

我也觉得有这种应用场景，有些用户就想开这个页面，没有其它的视觉干扰（如编辑器）
