### ISSUE TITLE
[Enhancement]: 编辑字体（包括字体，字号，颜色，背景色）时页面会出现偏移

### ISSUE THREAD

**Issue by Tian-Zhang** [toeverything/editoe#162]
## 问题描述

相关： #160 #158 
编辑字体（包括字体，字号，颜色，背景色）时页面会出现偏移，暂时看来是不规律的，第一次是除了编辑“字体大小”，其他三项点击后都会出现界面偏移的问题；第二次是“字体大小”和“字体颜色”不会出现偏移。
## 预期效果

不出现偏移就好
<hr>

如果你觉得这个改进很实用、很酷，请为此 Enhancement 点个:+1:

**Comment by L-Sun** [comment]
工具栏的图标均有这个问题

**Comment by L-Sun** [comment]
已修复
