### ISSUE TITLE
[Enhancement]: 新建文档位置改动及侧栏色彩调整

### ISSUE THREAD

**Issue by miuer970612-24** [toeverything/editoe#164]
## 问题描述
1. 新建文档按钮改至icon行最左侧
2. sidebar收起状态条背景色：F2F4F6
3. 选中指示条（看图）颜色及样式：11C3CC；5px；端点圆头
4. 将文献管理的指示icon换掉，已传公用设计文件
## 预期效果
![Lark20210318-142627](https://user-images.githubusercontent.com/79300922/111582559-f873ad80-87f5-11eb-9212-2baa85c2eab7.png)

<hr>

如果你觉得这个改进很实用、很酷，请为此 Enhancement 点个:+1:

**Comment by L-Sun** [comment]
已修改
