### ISSUE TITLE
[Enhancement]: 右键菜单添加新建文档功能

### ISSUE THREAD

**Issue by miuer970612-24** [toeverything/editoe#165]
## 预期效果

<hr>

如果你觉得这个改进很实用、很酷，请为此 Enhancement 点个:+1:

**Comment by chenyang9725** [comment]
![image](https://user-images.githubusercontent.com/79300514/111593628-1a286100-8805-11eb-8a86-8844aa93014d.png)
似乎现在就有？ @miuer970612-24

**Comment by miuer970612-24** [comment]
@chenyang9725 我是指在这里加
![Lark20210318-162004](https://user-images.githubusercontent.com/79300922/111594285-d5e99080-8805-11eb-921b-e5136fee8547.png)

**Comment by L-Sun** [comment]
这里就不要加了把，右键菜单都是和内容相关的东西

**Comment by miuer970612-24** [comment]
这个周一产品会讨论一下

**Comment by unknownuser1-1** [comment]
将在其他地方调整位置
