### ISSUE TITLE
[BUG]: 公式换行后无法移动回上一行

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#168]
### 问题描述
公式换行后无法移动回上一行，光标无法置于公式之前。

![图片](https://user-images.githubusercontent.com/79503478/111739543-2f14fb00-88be-11eb-9372-19e58f22ba2f.png)

### 运行环境
- 操作系统版本: 
- 浏览器版本:

## 复现步骤:

1. 
2.

**Comment by L-Sun** [comment]
已修复
