### ISSUE TITLE
分享链接，匿名用户无法打开

### ISSUE THREAD

**Issue by niudai** [toeverything/editoe#17]
- 操作系统版本: 
- 浏览器版本: 

复现步骤:

点击这里分享了文档：

![image](https://user-images.githubusercontent.com/44165182/108585920-2516df80-7386-11eb-9496-877657e16d2b.png)

但是在未登录的网页中打不开，请求报 500 internal error：

![image](https://user-images.githubusercontent.com/44165182/108585931-3d86fa00-7386-11eb-9f58-957fbceeecd1.png)

**Comment by L-Sun** [comment]
Fixed.
