### ISSUE TITLE
[BUG]: 在一行内纯输数字或字母会扩大编辑界面

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#170]
### 问题描述

在一行内纯输数字或字母会扩大编辑界面，如下图。此时文本将被左右侧栏遮挡。

但单纯输入汉字不会。如果确需扩大编辑界面，则需要解决文本被遮挡问题。
### 运行环境
- 操作系统版本: win10
- 浏览器版本:edge

## 复现步骤:

1. 
2. 

### 实际效果:
![图片](https://user-images.githubusercontent.com/79503478/111754123-976dd780-88d2-11eb-9e1d-edfcf68d774f.png)

**Comment by unknownuser1-1** [comment]
#157

**Comment by L-Sun** [comment]
已修复
