### ISSUE TITLE
[BUG]: 小屏幕下表格会有意外的边距

### ISSUE THREAD

**Issue by L-Sun** [toeverything/editoe#173]
### 问题描述

表格内容很多时候，滚动条和表格会有很大的边距

### 运行环境
- 操作系统版本: Windows 10
- 浏览器版本: Edge

## 复现步骤:

1. 创建一个多列的表格
2. 输入足够的的内容，直到出现滚动条
3. 意外的边距出现

### 预期效果:

![预期效果](https://user-images.githubusercontent.com/20479050/111807390-dbca9900-890d-11eb-9a60-52d175252c29.png)

### 实际效果:

![实际效果](https://user-images.githubusercontent.com/20479050/111807301-c7869c00-890d-11eb-93a4-de8c19ff1f4b.png)

**Comment by unknownuser1-1** [comment]
相关问题：https://github.com/toeverything/editoe/issues/157
https://github.com/toeverything/editoe/issues/170

**Comment by L-Sun** [comment]
已修复
