### ISSUE TITLE
[BUG]: 列表内存在自动换行故障

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#175]
### 问题描述
在无序和有序列表中，存在二级列表（或者三级、四级。。）时，点击二级列表前方，会自动换行，取消二级列表并留下一个空行。

待办列表不存在此问题，但点击二级列表下方的一级列表时，也会自动换行。

**为什么重要**：在用户试图选择部分二级列表内容时，会完全破坏二级列表，使得用户无法正常编辑

### 运行环境
- 操作系统版本: win10
- 浏览器版本:edge

## 复现步骤:
https://www.awesomescreenshot.com/video/3134484?key=46047b70c35795d9f30a8c91f6e870bf

### 预期效果:

点击这些地方应该不存在这些反应。

**Comment by L-Sun** [comment]
@Ryan-yang125 尝试将”点击换行“做成可配置，数组中的元素之间才能激活这个功能
