### ISSUE TITLE
[BUG]: 重命名文件夹不刷新即无效果

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#177]
### 问题描述

重命名文件夹后，文件夹名称的修改不会立刻呈现，必须刷新页面。

容易让用户以为没有修改成功。
### 运行环境
- 操作系统版本: win10
- 浏览器版本:edge

## 复现步骤:

1. 
2.

**Comment by chenyang9725** [comment]
该bug没有复现
