### ISSUE TITLE
右侧 Sidebar 不容易引起用户的注意

### ISSUE THREAD

**Issue by niudai** [toeverything/editoe#18]
新用户不容易注意到这个：
怎么办？

![image](https://user-images.githubusercontent.com/44165182/108586128-678cec00-7387-11eb-83cf-8266c83e6ad4.png)

我的建议：

模仿 VSCode，首先把图标变大，然后做一个有背景色的 Activity Bar

![image](https://user-images.githubusercontent.com/44165182/108586166-a3c04c80-7387-11eb-9e2d-7c81b93a5be6.png)

只不过我们放在右侧就行。

**Comment by L-Sun** [comment]
@niudai  进入页面的时候，默认展开是否可以？

**Comment by niudai** [comment]
好的，可以

**Comment by L-Sun** [comment]
![image](https://user-images.githubusercontent.com/20479050/108980928-2d915200-76c7-11eb-910c-db933119de37.png)

如果加上底色怎么样， @niudai @miuer970612-24

**Comment by niudai1998** [comment]
欸这个娅玮她们的新设计没和你说吗

**Comment by miuer970612-24** [comment]
已经重新设计，见蓝湖

**Comment by L-Sun** [comment]
已改善
