### ISSUE TITLE
[BUG]: 新建文件夹在移动时不显示，且存在莫名其妙的按钮导致页面崩溃

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#180]
### 问题描述

1. 新建文件夹之后，选择文档移动，不显示新建的文件夹，刷新无效（一天后还是没有显示）。
2. 且此时移动文档界面出现莫名其妙的按钮“新建文件夹”，点击后右侧栏完全崩溃。

问题1换手机号登陆后无法重现，可能需要明天测试微信号之后确定。问题2依旧存在。

### 运行环境
- 操作系统版本: win10
- 浏览器版本:edge

## 复现步骤:
https://www.awesomescreenshot.com/video/3135218?key=692ae46d4b02653e25ebd8733a58e35b

**Comment by chenyang9725** [comment]
fixed

**Comment by fangyuan-zheng** [comment]
@chenyang9725 现在点击这个按钮是没有任何功能的，是设计成这样的吗
![image](https://user-images.githubusercontent.com/79300990/115651403-acb8a480-a35d-11eb-93dd-8c6b0ba66e71.png)

**Comment by chenyang9725** [comment]
@fangyuan-zheng 新开个issue，已经closed就别管了
