### ISSUE TITLE
[BUG]: 移动文档后出现双重文档

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#181]
### 问题描述

将文档从“未归类文档”移动到一个文件夹之后，“未归类文档”中的文档不会消失（按理说此时已经归类），此时若删除新文件夹中的文档（此时本意是将该文档从此文件夹移除），“未归类文档”中的文档还会留存一阵，但点击的话就会弹出“无权访问”的提醒，返回原页面后，发现该文档已被删除。
### 运行环境
- 操作系统版本: win10
- 浏览器版本:edge

## 复现步骤:

https://user-images.githubusercontent.com/79503478/111947345-3e8f8080-8b18-11eb-867b-993071517f90.mp4

### 预期效果:

移动文档后文档从“未归类文档”中消失即可。

**Comment by chenyang9725** [comment]
该问题似乎也没有复现。。

**Comment by unknownuser1-1** [comment]
> 该问题似乎也没有复现。。

我微信能登陆了我再试试
