### ISSUE TITLE
[BUG]: 新建文档的页面，在小屏幕下布局出错

### ISSUE THREAD

**Issue by L-Sun** [toeverything/editoe#182]
### 问题描述

在屏幕小于1280px时，新建文档的的三个选项被遮挡，并且无法滚动到顶部

### 运行环境
- 操作系统版本: Windows 10
- 浏览器版本: Edge

## 复现步骤:

1. 登录
2. 点击立即开始
3. 把浏览器窗口缩小至1280px一下
4. 三个新建的按钮被遮挡，同时无法滚动到顶部

### 预期效果:

![image](https://user-images.githubusercontent.com/20479050/111948046-7e0a9c80-8b19-11eb-8e25-09f8fe8c26f8.png)

### 实际效果:

![image](https://user-images.githubusercontent.com/20479050/111948051-806cf680-8b19-11eb-9a2b-1dec520185e7.png)

**Comment by fangyuan-zheng** [comment]
fixed
