### ISSUE TITLE
[BUG]: 批量处理文档时显示故障

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#183]
### 问题描述

批量处理文档时显示效果不佳，存在按钮位置歪曲、重叠的情况
### 运行环境
- 操作系统版本: win10
- 浏览器版本:edge

## 复现步骤:
看图即可

### 预期效果:

较长文档名可以考虑缩略显示，不要把按钮挤到别的地方去。重叠的按钮需要再调整。
### 实际效果:
![图片](https://user-images.githubusercontent.com/79503478/112088277-7e16a500-8bca-11eb-8a9b-c70c67bae619.png)

**Comment by unknownuser1-1** [comment]
我这里还是有按钮重叠的问题。
![image](https://user-images.githubusercontent.com/79503478/112937118-ae75ba80-9159-11eb-8ee0-57ba122d9d05.png)

**Comment by chenyang9725** [comment]
fixed
