### ISSUE TITLE
[BUG]: 无法新建参考文献

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#184]
### 问题描述

不知道为什么现在似乎完全无法新建参考文献了，添加成功之后打开文件夹会瞬间消失。
### 运行环境
- 操作系统版本: win10
- 浏览器版本:edge

## 复现步骤:

1. 添加一个新参考文献
2. 打开所在文件夹

https://user-images.githubusercontent.com/79503478/112089424-9982af80-8bcc-11eb-8ac9-05820d86919d.mp4

**Comment by L-Sun** [comment]
@fangyuan-zheng 看看这个问题，这个bug直接导致文献管理的功能用不了

**Comment by L-Sun** [comment]
@fangyuan-zheng 有任何后端的问题，和 @wangyu654 交流

**Comment by fangyuan-zheng** [comment]
![image](https://user-images.githubusercontent.com/79300990/112176510-1e081900-8c33-11eb-884c-de899b196583.png)

**Comment by unknownuser1-1** [comment]
@fangyuan-zheng 现在好像还是不行，我这里连最开始那个“创建成功”也没有了
