### ISSUE TITLE
有没有开发VScode插件的形式的计划？左侧批量新建起来很方便

### ISSUE THREAD

**Issue by niudai** [toeverything/editoe#19]
有没有开发VScode插件的形式的计划？左侧批量新建起来很方便
![image](https://user-images.githubusercontent.com/71307974/108517487-741b3100-7302-11eb-9299-4fbf2ff2b19a.png)
，上面没有地址栏干扰，且可以直接操作本地文件。

_Originally posted by @StevenJokess in https://github.com/toeverything/editoe/issues/2#issuecomment-782097101_

sidebar 就是指这个

**Comment by StevenJokess** [comment]
@niudai 如果是以VScode插件的形式就很容易直接集成掉git协作了。
