### ISSUE TITLE
[Enhancement]: 登陆悬浮窗口异常提醒

### ISSUE THREAD

**Issue by niudai** [toeverything/editoe#194]
## 问题描述

因为验证码的发送有最小间隔事件（两分钟），希望在窗口上加上 倒计时，如果用户在两分钟内再次发送验证码，则应该有 ”您发送过快了，请过一会儿再发” 的提醒。

## 预期效果

<hr>

如果你觉得这个改进很实用、很酷，请为此 Enhancement 点个:+1:

**Comment by L-Sun** [comment]
已添加异常提醒
