### ISSUE TITLE
[BUG]: create页面无限请求/user接口

### ISSUE THREAD

**Issue by regischen** [toeverything/editoe#196]
### 问题描述

![image](https://user-images.githubusercontent.com/58546692/112784706-ed860c00-9084-11eb-85ec-986c3793f93e.png)

如图所示。
### 运行环境
- 操作系统版本: 
- 浏览器版本:

## 复现步骤:

1. 进入/create页面， 打开devTools，在未登录状态下查看网络请求
2.

**Comment by fangyuan-zheng** [comment]
已改
