### ISSUE TITLE
[BUG]: 正文参考文献之后无法插入光标

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#198]
### 问题描述

正文插入参考文献之后，后面完全无法插入光标。

**为什么严重**：如果此时参考文献后面没有文本，用户将**完全无法**继续编辑。
### 运行环境
- 操作系统版本: win10
- 浏览器版本:edge

## 复现步骤:

可以使用这个文档：https://canary.editoe.com/docs/doc3249be7ab255b85c#doc2857f9772b9959bf

### 预期效果:

可以插入光标

**Comment by chenyang9725** [comment]
现在是鼠标无法点击过去。。 可以有键盘移动光标移动

**Comment by unknownuser1-1** [comment]
且这时候也没办法用鼠标选择包括参考文献在内的文本，会有一个很奇怪的反弹效果，见视频：

https://user-images.githubusercontent.com/79503478/112820741-7d917900-90b8-11eb-9db6-f4e26a53ddd4.mp4

**Comment by unknownuser1-1** [comment]
感觉现在正文有很多非纯文本的文本内容（包括参考文献、外部链接、公式）都在选择时有选不中的情况，不知道这些问题是不是存在相似之处。

外部链接和公式的问题见：https://github.com/toeverything/editoe/issues/176

**Comment by L-Sun** [comment]
Fixed
