### ISSUE TITLE
Editoe 0.5 版本规划

### ISSUE THREAD

**Issue by niudai** [toeverything/editoe#2]
## Editoe 0.5 版本计划

> 本 issue 用于规划未来的研发计划，您可以在本 issue 下方评论，一起讨论开发路径。

记号 | 描述
-- | --
🏃 | 正在开发
💪 | 挑战性目标
🔵 | 需要进一步调研消除不确定性
⚫ | 团队正在进行功能设计
⬛ | 较大的 feature，可能需要多次版本迭代才能完成。

 ### 协作

- [x] ⚫支持内容分享
- [x] ⚫ 💪 支持同屏协作

### 内容创作

- [x] 🏃 补足尚未支持的 markdown 语法
- [x] 🏃 可在 Sidebar 中完成文档和文献的完整 创建，移动，删除 使用流，抛弃 文档/文献 大页。

### 专业内容

- [x] 🔵 类似 draw.io 的 GUI 绘图插件 

### 兼容

- [x] 🏃 Safari 浏览器兼容
- [x] 🏃 Firefox 浏览器兼容

### 格式转换

- [x] 支持多种常见导入格式：.doc  .markdown  .tex
- [x] 支持多种常见导出格式:   .doc  .pdf  .tex  .markdown

### 新手友好

- [x] 用户第一次使用，悬浮气泡教学指引

**Comment by StevenJokess** [comment]
有没有开发VScode插件的形式的计划？左侧批量新建起来很方便，上面没有地址栏干扰。

**Comment by L-Sun** [comment]
文档分享、是否需要展示two link关系？

**Comment by niudai** [comment]
@L-Sun 啥意思，分享不是引用呀，为啥会涉及 two link

**Comment by HeJiachen-PM** [comment]
> @L-Sun 啥意思，分享不是引用呀，为啥会涉及 two link

就是飞书的分享文章是有双向链接的，而且随人而变。如果直接显示可能会曝光用户隐私。

**Comment by HeJiachen-PM** [comment]
内容创作中需要支持更丰富的样式，比如：
- 双栏模式
- 分页
- 分章
- 脚注与边注
- shaded box？
