### ISSUE TITLE
[BUG]: 利用复选功能删除文件，没有及时更新列表

### ISSUE THREAD

**Issue by L-Sun** [toeverything/editoe#204]
### 运行环境
- 操作系统版本: Windows 10
- 浏览器版本: Edge

## 复现步骤:

1. 在根目录下用复选功能选中多个文件
2. 点击删除，（此时没有更新列表）
3. 再用复选功能选中其它文件，此时之前的文件依然是被勾选的（我会认为这些文件没有被删除成功，就想再删除一次试试）。
4. 再次点删除
5. 抛出错误

### 预期效果:

能够及时更新删除后的文件列表

### 实际效果:
被删除的文件依然还在列表中，并且尝试再次去删除这些文件，就会抛出错误。

**Comment by unknownuser1-1** [comment]
感觉和我之前测出来的https://github.com/toeverything/editoe/issues/181 有点像，不过我那个换了台电脑就不能复现了

**Comment by chenyang9725** [comment]
fixed
