### ISSUE TITLE
[Enhancement]: 移动端首页样式问题

### ISSUE THREAD

**Issue by niudai** [toeverything/editoe#205]
## 问题描述

移动端出现了两个问题：

![微信图片_20210401110240](https://user-images.githubusercontent.com/44165182/113237664-d4c26400-92d9-11eb-905a-87039fd00e78.jpg)
![微信图片_20210401110248](https://user-images.githubusercontent.com/44165182/113237669-d68c2780-92d9-11eb-8aaa-c73d337ced13.jpg)

一个是移动端应该没有上面的四个按钮，况且也确实塞不下。

第二个是 在这里编辑你的万物理论 这个东西应该是个固定大小的 svg，直接把屏幕撑宽了，还能横向拖动，严重影响观感。

## 预期效果

符合设计图的样子就行。

<hr>

如果你觉得这个改进很实用、很酷，请为此 Enhancement 点个:+1:

**Comment by fangyuan-zheng** [comment]
好的，这个今天早上刚改完，还没有合并

**Comment by fangyuan-zheng** [comment]
​ @王娅玮​ 娅玮“编辑你的万物理论”能给个svg图吗
