### ISSUE TITLE
[Enhancement]: 编辑器首页需要“投光编辑器”字样

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#206]
## 问题描述

因SEO故障，加上中文用户居多，3月初周会上应当已一致同意开始在首页等其他地方优先使用或至少加上“投光编辑器”字样，后来可能是被忘了，刚和设计重新提过了，需要0.5实现。
## 预期效果

<hr>

如果你觉得这个改进很实用、很酷，请为此 Enhancement 点个:+1:

**Comment by fangyuan-zheng** [comment]
已和设计完成

**Comment by unknownuser1-1** [comment]
好像效果和原来设计的不一样

**Comment by unknownuser1-1** [comment]
小屏幕下显示效果极差（如果改rem来不及还得出其他解决方案）：
![图片](https://user-images.githubusercontent.com/79503478/113510322-e2534480-958c-11eb-96ce-499cbe7a63bf.png)
