### ISSUE TITLE
[BUG]: 未注册用户直接使用微信登陆会导致无法使用

### ISSUE THREAD

**Issue by Ryan-yang125** [toeverything/editoe#207]
### 问题描述

未注册用户直接使用微信登陆会导致无法使用
### 运行环境
- 操作系统版本: 
- 浏览器版本:

## 复现步骤:

1. 未注册用户直接使用微信登陆显示登陆失败
2. 返回使用邀请码和验证码注册，显示注册成功，但还是未登陆状态
3. 并且之后始终无法登陆

### 实际效果:
提示登陆成功，页面仍为未登陆状态

**Comment by chenyang9725** [comment]
fixed 目前用微信登录，第一次需要绑定手机号
