### ISSUE TITLE
[BUG]: 新建空白文档失败

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#208]
### 问题描述

1.在文档编辑界面新建文档失败，见https://www.awesomescreenshot.com/video/3256091?key=9816b74f5859310cde25a6a3c1ac623c

2.我的账号已建立了其他文档：此时从我的空间点击新建“空白文档”，显示“创建失败”（有时候干脆不显示），并跳转到最近编辑的文档。见https://www.awesomescreenshot.com/video/3255906?key=b8547824ccae764d8cf3f8ee438d14a1

可能也需要测试在没建立其他文档时为什么效果。
### 运行环境
- 操作系统版本: win10
- 浏览器版本:edge

**Comment by chenyang9725** [comment]
![image](https://user-images.githubusercontent.com/79300514/113651730-1c276680-96c5-11eb-96cb-aff9e6e12233.png)
找不到视频了。。 oops

**Comment by unknownuser1-1** [comment]
> ![image](https://user-images.githubusercontent.com/79300514/113651730-1c276680-96c5-11eb-96cb-aff9e6e12233.png)
> 找不到视频了。。 oops

再试一下

**Comment by unknownuser1-1** [comment]
@chenyang9725 应该是被修复了
