### ISSUE TITLE
关于sidebar-timeline的feature完善提案

### ISSUE THREAD

**Issue by miuer970612-24** [toeverything/editoe#21]
1 每个文献内笔记写到后面（字数很多的情况下）的状况-参考飞书个人签名的处理方式，建议不要多加一个带边框的文本框
2 手动添加文献成功后需要有定位闪烁
3 第一次（没有任何文献的情况下），不应该是空值页，而是引导用户去添加第一个文件夹的按钮-采用文献管理页的加号组件

**Comment by fangyuan-zheng** [comment]
3、在timeline底部添加按钮，实现文件夹创建，效果还需修改

**Comment by fangyuan-zheng** [comment]
- [ ] 1、 每个文献内笔记写到后面（字数很多的情况下）的状况-参考飞书个人签名的处理方式，建议不要多加一个带边框的文本框
- [ ] 2、手动添加文献成功后需要有定位闪烁
- [ ] 4、note容器自动适应note文本
