### ISSUE TITLE
编辑器ctrl-A到word，会把一些没有在页面的部分粘贴进去

### ISSUE THREAD

**Issue by Yipei-Operation** [toeverything/editoe#211]
![image](https://user-images.githubusercontent.com/79373028/113437145-adbe7c00-9418-11eb-9982-65c256d4b7e7.png)
ru如文件列表那部分，其实当时在页面没有显示，但是ctrl-A复制到word就会带出一些文本以外的部分。

**Comment by L-Sun** [comment]
已修复
