### ISSUE TITLE
[BUG]:重复菜单栏

### ISSUE THREAD

**Issue by fangyuan-zheng** [toeverything/editoe#212]
### 问题描述
右键唤醒第一个菜单栏，再唤醒第二个菜单栏出现两个菜单同时出现
![image](https://user-images.githubusercontent.com/79300990/113499839-cc715f80-954b-11eb-996a-61f24fde4cee.png)

### 运行环境
- 操作系统版本: 
- 浏览器版本:

## 复现步骤:

1. 
2.

**Comment by chenyang9725** [comment]
fixed
