### ISSUE TITLE
右侧sidebar文献管理中直接添加文献失效

### ISSUE THREAD

**Issue by HeJiachen-PM** [toeverything/editoe#22]
- 操作系统版本: macOS Catalina
- 浏览器版本: Edge Chrominum

复现步骤:

![image](https://user-images.githubusercontent.com/79301703/108590221-391a0b80-739d-11eb-88f5-758edf27c70c.png)

1.点击右侧文献管理
2.点击加号，并填充所有必要域

**Comment by HeJiachen-PM** [comment]
与日期相关，似乎0101才会触发

**Comment by L-Sun** [comment]
已修复
