### ISSUE TITLE
[BUG]: 我的文档中没有文档时，进入/回到中转页会自动新建空白文档并进入编辑页面

### ISSUE THREAD

**Issue by Moqqll** [toeverything/editoe#220]
### 问题描述

我的文档中没有文档时，进入/回到中转页会自动新建空白文档并进入编辑页面
### 运行环境
- 操作系统版本: win10 20H2
- 浏览器版本:Google89.0.4389.114

## 复现步骤:

1. 我的文档中没有文档（有文档时该bug不会出现） 
![image](https://user-images.githubusercontent.com/68946469/113685744-2400fe00-96f9-11eb-80f8-ea455a8b9a24.png)
2. 回到/进入中转页会自动新建空白文档并在浏览器未阻止弹窗时打开文档编辑页面
![image](https://user-images.githubusercontent.com/68946469/113685808-35e2a100-96f9-11eb-879b-ff9977a43e6a.png)

### 预期效果:

回到/进入中转页，应该不做自动新建空白文档的操作
### 实际效果:
我的文档中没有文档时，进入/回到中转页会自动新建空白文档并进入编辑页面

**Comment by fangyuan-zheng** [comment]
已改
