### ISSUE TITLE
[BUG]: 头像-邀请码 这边的显示好像全部不对劲

### ISSUE THREAD

**Issue by YaweiWangTOE** [toeverything/editoe#223]
### 问题描述

![image](https://user-images.githubusercontent.com/79351864/113825946-2d9b6c00-97b4-11eb-911d-7ea5dce4926a.png)

### 运行环境
- 操作系统版本: win 10
- 浏览器版本:chrome

文档数目对不上，邀请码好像也对不上

**Comment by L-Sun** [comment]
新建一个文档后，这里是否会变化？

**Comment by YaweiWangTOE** [comment]
> 新建一个文档后，这里是否会变化？

没有变化
