### ISSUE TITLE
[BUG]: 启用列表的情况下无法继续在正文打字

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#225]
### 问题描述

键入列表之后，**若底部没有内容**，无法通过退格键删除列表，也无法通过鼠标点击、移动光标进入正文，要退出表格模式必须再次回车。这非常不符合用户逻辑。

最好能在0.6上线前修正。
### 运行环境
- 操作系统版本: win10
- 浏览器版本:edge

## 复现步骤:

https://www.awesomescreenshot.com/video/3297696?key=13edbc43b8b0781d4402521d26066562

### 预期效果:

https://www.awesomescreenshot.com/video/3297787?key=c22bbb5e6b5d2c2db15936b2e4c113b3

**Comment by chenyang9725** [comment]
按两次回车可以退出列表，

**Comment by chenyang9725** [comment]
@niudai @L-Sun @Ryan-yang125 怎么看

**Comment by Ryan-yang125** [comment]
我赞成不改，markdown的语法就是这样的

**Comment by unknownuser1-1** [comment]
这是一个用户逻辑问题，如果证明绝大多数用户都能想到退出列表不能用退格而是回车，那我也没意见
