### ISSUE TITLE
[BUG]: 给具有标题属性的文字添加列表样式时，标题属性会消失

### ISSUE THREAD

**Issue by YaweiWangTOE** [toeverything/editoe#229]
### 问题描述

https://user-images.githubusercontent.com/79351864/114127734-6448c200-992d-11eb-8e31-34a6c2a6afcd.mp4

### 运行环境
- 操作系统版本: win10
- 浏览器版本:chrome

### 预期效果:
保留标题样式

**Comment by unknownuser1-1** [comment]
就是https://github.com/toeverything/editoe/issues/161
