### ISSUE TITLE
右侧文献管理titile最大宽度过窄,无法显示标题全长

### ISSUE THREAD

**Issue by HeJiachen-PM** [toeverything/editoe#23]
- 操作系统版本: macOS
- 浏览器版本: edge chromium
*怀疑有缩放问题, 有待测试, 不在本issue讨论*

复现步骤:

![image](https://user-images.githubusercontent.com/79301703/108590401-54394b00-739e-11eb-8236-2efbfb5f8aa9.png)

1.点击文献管理插件
2.拉宽

**Comment by fangyuan-zheng** [comment]
标题的展开由右侧按头控制，点击按钮展开详情
![image](https://user-images.githubusercontent.com/79300990/108809579-22192a80-75e4-11eb-8ebb-cdc33289b1e1.png)
![image](https://user-images.githubusercontent.com/79300990/108809680-55f45000-75e4-11eb-8712-f5fb4338f095.png)
