### ISSUE TITLE
[FeatureRequest]: 行距调整功能

### ISSUE THREAD

**Issue by Afool1999** [toeverything/editoe#232]
### 功能描述

Markdown 和 Latex (Word) 的区别在于 Latex (Word)可以更精确的控制排版。在不加修改 css 的情况下，Markdown 导出的结果虽然看得很舒服，但行距过宽，不适合用来写 paper，学术编辑的话可能支持行距调整更好。
<hr>

如果你觉得这个功能很实用、很酷，请为此 Featrue 点个:+1:

**Comment by fangyuan-zheng** [comment]
您的问题我们已经看到，请问怎么closed了呢？
