### ISSUE TITLE
编辑器内顶栏样式在缩放后会重叠

### ISSUE THREAD

**Issue by HeJiachen-PM** [toeverything/editoe#24]
- 操作系统版本: macOS
- 浏览器版本: edge chromium

复现步骤:

![image](https://user-images.githubusercontent.com/79301703/108590586-4f28cb80-739f-11eb-9dfd-36b22c4c9c07.png)

1.试用“ctrl" + "+"进行缩放，直到错位

**Comment by L-Sun** [comment]
属于和移动端适配的同类问题

**Comment by L-Sun** [comment]
已修复
