### ISSUE TITLE
[Enhancement]: uml制图表格内无法换行 （贺维格提出）

### ISSUE THREAD

**Issue by fangyuan-zheng** [toeverything/editoe#242]
## 问题描述
在表中按enter键，光标换行，希望是在表格内部换行，而现在按下enter键是在画布上换行。
![GIF](https://user-images.githubusercontent.com/79300990/114196939-6ee27600-9984-11eb-925b-0e19a6511a92.gif)

## 预期效果
如下，可以在表格内部实现换行
![GIF](https://user-images.githubusercontent.com/79300990/114197755-3d1ddf00-9985-11eb-950a-2c7e2f6b735c.gif)

<hr>

如果你觉得这个改进很实用、很酷，请为此 Enhancement 点个:+1:

**Comment by whheweige** [comment]
表述完全正确，不过我还没有试其他UML图是否也存在这个问题，请把测试其他UML图是否用同样问题加入to do list
