### ISSUE TITLE
[BUG]: uml制图bug （贺维格提）

### ISSUE THREAD

**Issue by fangyuan-zheng** [toeverything/editoe#244]
### 问题描述
uml中选择synchronous invocation，选中文本，直接按下enter键，会出现光标累积成一条黑线

### 运行环境
- 操作系统版本: chrome
- 浏览器版本:

## 复现步骤:
选择如下几个制图，都会出现
![image](https://user-images.githubusercontent.com/79300990/114201846-37c29380-9989-11eb-90cd-23fe77fda469.png)
![GIF](https://user-images.githubusercontent.com/79300990/114201773-24172d00-9989-11eb-9ac4-95ac1146f461.gif)

**Comment by whheweige** [comment]
表述完全正确，不过我还没有试其他UML图是否也存在这个问题，请把这个加入to do list
