### ISSUE TITLE
[BUG]: 绘制图表有时候无法保存到编辑器

### ISSUE THREAD

**Issue by whheweige** [toeverything/editoe#250]
### 问题描述
<绘制图表有时候无法保存到编辑器，尝试多次，有时候成功有时候不成功，性能不稳定
   如果编辑器中没有点击，即没有那个竖线 |，那么图表是无法保存的>

### 运行环境
- 操作系统版本: 
- 浏览器版本:

## 复现步骤:

1. 
2.

**Comment by L-Sun** [comment]
这个问题已经修复
