### ISSUE TITLE
文档分享功能

### ISSUE THREAD

**Issue by Gakiii** [toeverything/editoe#252]
像Notion编辑完一个文档之后，可以选择将文档放在互联网上供其他人查看，不知道投光是否可以出一个这个类似的功能
@HeJiachen-PM  @L-Sun @niudai @unknownuser1-1

**Comment by HeJiachen-PM** [comment]
我们已有这个功能啦

**Comment by unknownuser1-1** [comment]
同https://github.com/toeverything/editoe/issues/217 @HeJiachen-PM 现在是虽然可分享，但是必须登录
