### ISSUE TITLE
[BUG]: 无法继续正常输入

### ISSUE THREAD

**Issue by TsuiEnPeng** [toeverything/editoe#253]
### 问题描述

当我写了一个@xxxx 之后，后面的内容都会被自动选定，没办法切换成正常输入的模式
### 运行环境
- 操作系统版本: MacOS 10.15.7
- 浏览器版本: Chrome 89.0.4389.114（正式版本） (x86_64)

## 复现步骤:

1. 
2. 

### 预期效果:

@xxx  正常输入文本内容
### 实际效果:
![截屏2021-04-10 下午12 37 54](https://user-images.githubusercontent.com/38204629/114258559-dedf1380-99f9-11eb-8349-0080242507e3.png)
一直处于灰色的被选中的状态

**Comment by unknownuser1-1** [comment]
我这里win10似乎无法重现

**Comment by TsuiEnPeng** [comment]
刷新一下页面就好了...

**Comment by HeJiachen-PM** [comment]
我们会用mac OS尝试复现
