### ISSUE TITLE
[BUG]: 从谷歌学术复制的bibtex识别不了

### ISSUE THREAD

**Issue by fangyuan-zheng** [toeverything/editoe#255]
### 问题描述
从谷歌学术复制的bibtex识别不了，说缺少 jornaltitle
![image](https://user-images.githubusercontent.com/79300990/114259433-7a738280-9a00-11eb-8883-7f25db88e082.png)

**Comment by unknownuser1-1** [comment]
参考文献问题还很多，下周一块修
