### ISSUE TITLE
[FeatureRequest]: 国外手机号绑定

### ISSUE THREAD

**Issue by whheweige** [toeverything/editoe#258]
### 问题描述
<微信扫进去之后仍然需要手机号绑定>

### 运行环境
- 操作系统版本: IOS
- 浏览器版本:CHROME

## 复现步骤:

1. 如果没有国内手机号仍然无法使用，那好像微信登入这个渠道其实是无效的？

2.

**Comment by unknownuser1-1** [comment]
现在实质上就是必须要手机注册，利用微信注册的好处是以后可以直接扫码而已。

现在国外手机不能注册吗？不知道技术部门这边能不能出个解决方案，现在有一些种子用户实际上是在国外的，像我之前虽然有国内手机，但其实是停机状态。 @niudai

**Comment by whheweige** [comment]
国外手机不可以注册目前，这是我朋友的反馈。但是我大部分邀请的测试者都在国外，可能这边就没办法反馈了，我再去找国内的朋友帮我做测试反馈吧。
这个也不着急，因为我们目前针对的是国内用户，如果这个问题修改起来比较复杂，我认为可以暂时搁置这个enhancement。周一可以讨论一下。
谢谢回复。


维格
祝安



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月11日(周日) 凌晨0:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [toeverything/editoe] [BUG]: 微信扫进去之后仍然需要手机号绑定 (#258)




 
现在实质上就是必须要手机注册，利用微信注册的好处是以后可以直接扫码而已。
 
现在国外手机不能注册吗？不知道技术部门这边能不能出个解决方案，现在有一些种子用户实际上是在国外的，像我之前虽然有国内手机，但其实是停机状态。 @niudai

**Comment by whheweige** [comment]
国内手机如果要在国外用，需要开通国际漫游


维格
祝安



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月11日(周日) 凌晨0:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [toeverything/editoe] [BUG]: 微信扫进去之后仍然需要手机号绑定 (#258)




 
现在实质上就是必须要手机注册，利用微信注册的好处是以后可以直接扫码而已。
 
现在国外手机不能注册吗？不知道技术部门这边能不能出个解决方案，现在有一些种子用户实际上是在国外的，像我之前虽然有国内手机，但其实是停机状态。 @niudai

**Comment by unknownuser1-1** [comment]
同https://github.com/toeverything/editoe/issues/235

**Comment by unknownuser1-1** [comment]
和https://github.com/toeverything/editoe/issues/235 一样，暂时关闭
