### ISSUE TITLE
[BUG]: 。。裂开，导出markdown文档后网页保存的文档变成空白，而且导出的文件的引用代码部分不见了，只留下大纲的文字

### ISSUE THREAD

**Issue by soda-available** [toeverything/editoe#266]

**Comment by niudai** [comment]
收到，我们马上会做一个离线备份的机制保证您的内容断网不丢失。

**Comment by niudai** [comment]
您好，请发下文档的链接~ 谢谢~

**Comment by soda-available** [comment]
现在网页可以看到文档了(markdwon代码部分不见了，和导出的文档内容残缺部分一样
https://editoe.com/docs/docb4f3dc4a740d6157





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "toeverything/editoe"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月12日(星期一) 晚上6:45
***@***.***&gt;;
抄送:&nbsp;"国贸1901 赵强 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [toeverything/editoe] [BUG]: 。。裂开，导出markdown文档后网页保存的文档变成空白，而且导出的文件的引用代码部分不见了，只留下大纲的文字 (#266)





 
您好，请发下文档的链接~ 谢谢~

**Comment by niudai1998** [comment]
好的，新的代码块已经不会丢失了，这个 bug 今天刚修复
