### ISSUE TITLE
markdown语法复制进编辑器bug

### ISSUE THREAD

**Issue by fangyuan-zheng** [toeverything/editoe#270]
### 问题描述
将一段markdown语法复制到编辑器，编辑器将会丢失。页面上出现图二的情况，只出现一个代码框，内容丢失
![image](https://user-images.githubusercontent.com/79300990/114356335-0d4c2280-9ba3-11eb-90de-bd6094399490.png)
![image](https://user-images.githubusercontent.com/79300990/114356189-e7268280-9ba2-11eb-9ada-844acbfeb66c.png)

### 运行环境
- 操作系统版本:  windows
- 浏览器版本:  chrome/edge

### 预期效果:
![image](https://user-images.githubusercontent.com/79300990/114356702-80ee2f80-9ba3-11eb-8586-7c232953f114.png)

**Comment by L-Sun** [comment]
已修复
