### ISSUE TITLE
[Enhancement]: 支持画交换图

### ISSUE THREAD

**Issue by Jingzhenzxz** [toeverything/editoe#272]
## 问题描述

支持画交换图

## 预期效果

![image](https://user-images.githubusercontent.com/47069834/114483907-ceb67680-9c3b-11eb-9e89-cdcca2714131.png)

<hr>

如果你觉得这个改进很实用、很酷，请为此 Enhancement 点个:+1:

**Comment by L-Sun** [comment]
目前并不支持使用 amscd 包。不过在未来的版本，会加入 Tikz 的绘图功能
