### ISSUE TITLE
[Enhancement]: 允许切换为源代码模式。

### ISSUE THREAD

**Issue by Jingzhenzxz** [toeverything/editoe#273]
## 问题描述

允许切换为源代码模式

## 预期效果

![image](https://user-images.githubusercontent.com/47069834/114484500-ea6e4c80-9c3c-11eb-94d7-273ad80a22a6.png)

<hr>

如果你觉得这个改进很实用、很酷，请为此 Enhancement 点个:+1:

**Comment by L-Sun** [comment]
这里按在$ _任意公式_ $后面打个空格就会渲染公式，如果想要获取公式源代码，可以点击公式按复制、或者双击公式打开输入面板。
