### ISSUE TITLE
[Enhancement]: 不用按回车键就能生成新的一行。

### ISSUE THREAD

**Issue by Jingzhenzxz** [toeverything/editoe#274]
## 问题描述

不用按回车键就能生成新的一行。

## 预期效果

在Typora中，把光标挪到新的一行只需要用鼠标点一下空白区域即可，不用按回车键。
![image](https://user-images.githubusercontent.com/47069834/114485094-f1498f00-9c3d-11eb-9b89-815af89fa0e1.png)

<hr>

如果你觉得这个改进很实用、很酷，请为此 Enhancement 点个:+1:

**Comment by L-Sun** [comment]
@Ryan-yang125 这个看看，试下弄成文末无论是什么元素都能点击加入新的一行
