### ISSUE TITLE
加大标题字号有助于改善可读性，同时建议首行标题额外加大，默认为文章title

### ISSUE THREAD

**Issue by HeJiachen-PM** [toeverything/editoe#28]
如图所示，飞书的字号设置写出的可读性好于editoe
![image](https://user-images.githubusercontent.com/79301703/108602640-f9bfdf00-73dd-11eb-9752-c1aaee5d3fc3.png)
![image](https://user-images.githubusercontent.com/79301703/108602644-00e6ed00-73de-11eb-939b-261deb6b5353.png)

**Comment by HeJiachen-PM** [comment]
此外，飞书似乎也控制了title上下的留白距离。

**Comment by L-Sun** [comment]
这应该是行距字号的问题，可以看看怎么调整 @miuer970612-24 ，可以找 @fangyuan-zheng 协助在浏览器上实时调整字号、间距等尺寸

**Comment by miuer970612-24** [comment]
@chenyang9725 标题和正文第一行的间距可以再大一些
![Lark20210302-104840](https://user-images.githubusercontent.com/79300922/109589206-ed0d5a80-7b44-11eb-9b20-bfbc767fe012.png)
