### ISSUE TITLE
绘图保存后无法再次编辑

### ISSUE THREAD

**Issue by yuqi-lee** [toeverything/editoe#284]
### 运行环境
- 操作系统版本: macintosh 10.15
- 浏览器版本: safari

## 复现步骤:

1. 使用绘图功能并保存
2. 继续编辑该图片

### 预期效果:

在刚刚绘图基础上，可以继续创作
### 实际效果:
出错
非绘图文件 (error on line 6 at column 8: Opening and ending tag mismatch: hr line 0 and body)

**Comment by niudai** [comment]
已经修复，新的图不会出现此问题。
