### ISSUE TITLE
新建文献夹成功后响应时间太久

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#285]
### 问题描述

新建文献夹成功后。文献夹不会立刻出现，必须等待一阵时间或刷新页面，若在此之前尝试建立同名文献夹，显示创建失败。

新建的文献本身也不会在@的菜单栏中立刻出现。

已在多台计算机上复现。
### 运行环境
- 操作系统版本: 
- 浏览器版本:

## 复现步骤:
https://www.awesomescreenshot.com/video/3388216?key=42252c81cb42bc69c272fa6bfc2554af

### 预期效果:

- 新建文献夹成功后立刻出现
- 创建同名文献夹时需要清晰的警告“已存在同名文献夹”

**Comment by fangyuan-zheng** [comment]
第一个问题你是再canary上还是editoe上
