### ISSUE TITLE
[Enhancement]: 能否支持笔记文件存储在Dropbox、Google Drive、坚果云、OneDrive等网盘？

### ISSUE THREAD

**Issue by dourgey** [toeverything/editoe#286]
## 问题描述
希望能设置笔记文件存储在包括但不仅限于Dropbox、Google Drive、坚果云、OneDrive等个人网盘，并且在修改后自动更新文件。

## 预期效果
实现个人账号绑定包括但不仅限于上述网盘后，从相关网盘中自动读取笔记文件，在用户使用编辑器修改文件后自动将最新版本（也可以附带历史版本）更新至网盘，以实现笔记文件在个人网盘中的备份管理。

<hr>

如果你觉得这个改进很实用、很酷，请为此 Enhancement 点个:+1:

**Comment by HeJiachen-PM** [comment]
这将会成为付费功能。 投光 贺嘉琛
