### ISSUE TITLE
行间公式无法转为行内公式

### ISSUE THREAD

**Issue by Yipei-Operation** [toeverything/editoe#29]
- 操作系统版本: Windows10
- 浏览器版本: Edge

复现步骤:

在行内公式转为行间公式后，无法转回行内公式

另外，在全文复制粘贴时，很多公式无法识别，是否考虑全文粘贴时提供弹窗选择自动转换？

**Comment by L-Sun** [comment]
@Yipei-Operation 
1. 可以点击公式，在面板种按下快捷键<kbd>Ctrl</kbd> + <kbd>M</kbd>来进行切换
2. 目前阶段暂时不考虑粘贴时，提示用户是否自动转换数学公式；目前在考虑用更简单的方法来转换公式。
