### ISSUE TITLE
[Enhancement]: 文件管理页面bug

### ISSUE THREAD

**Issue by fangyuan-zheng** [toeverything/editoe#292]
### 问题描述
“绘图”功能场景下，拼音打字，敲出的第一个字母，会被指定为英文。

### 运行环境
- 操作系统版本: 
- 浏览器版本:（搜狗浏览器10.0.2.33514 Chrome内核高速模式 win7）

## 复现步骤:

1. 
2.

**Comment by chenyang9725** [comment]
文不对题
