### ISSUE TITLE
退出再登录会闪现下面页面（维格提）

### ISSUE THREAD

**Issue by fangyuan-zheng** [toeverything/editoe#294]
### 问题描述
退出再登录会闪现下面页面
![image](https://user-images.githubusercontent.com/79300990/115000483-62ef3a80-9ed5-11eb-8cd5-548db5a60f7b.png)

## 复现步骤:

1. 编辑器页面点击退出登录，页面跳转到用户验证页面
2. 在使用之前的账号登录，加载过程中会出现如上权限提示页面

### 预期效果:
不要跳出权限提示页面

**Comment by unknownuser1-1** [comment]
同https://github.com/toeverything/editoe/issues/217 问2
