### ISSUE TITLE
canary右下角条幅遮挡工具栏

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#304]
### 问题描述

**由于下述问题2的存在，希望能尽快解决：**

现在条幅放在页面最上层，这导致：
1.遮挡文字，
2.光标若置于此处，无法进行任何操作，包括点击本来位于此地的文档。

### 运行环境
- 操作系统版本: win10
- 浏览器版本:edge

## 复现步骤:

1. 
2. 

### 预期效果:

需要
1).默认在右侧工具栏下，
或者2).考虑搞成底部/顶部悬浮条（这样占用空间小，但也显眼，置顶在最上层应该也不会有问题，且看下图实际还可以选择关闭（这点现阶段做不做到随便了））

处理方法2可以参考：
![图片](https://user-images.githubusercontent.com/79503478/115120290-5ce58080-9fdf-11eb-9536-773de16e6933.png)

### 实际效果:
![图片](https://user-images.githubusercontent.com/79503478/115120326-7f779980-9fdf-11eb-9ce3-5d91bbeae8dd.png)

**Comment by HeJiachen-PM** [comment]
需要稍微调高透明度，且设置成不影响下层点击。

**Comment by fangyuan-zheng** [comment]
和工具条重合的文件点不开
![GIF](https://user-images.githubusercontent.com/79300990/115336077-0a6bb600-a1d1-11eb-8bea-bab996adee20.gif)
