### ISSUE TITLE
bibtex导入问题

### ISSUE THREAD

**Issue by fangyuan-zheng** [toeverything/editoe#308]
### 问题描述
![image](https://user-images.githubusercontent.com/79300990/115192594-991efb00-a11d-11eb-8907-2f6e7a169621.png)

### 运行环境
- 操作系统版本: 
- 浏览器版本:

## 复现步骤:

1. 
2.

**Comment by Spacewe-outlook** [comment]
导入添加不了，按钮比较生硬。

**Comment by HeJiachen-PM** [comment]
> 导入添加不了，按钮比较生硬。

已修复功能，按钮会在下版本更新
