### ISSUE TITLE
[Enhancement]: 文章应该有scrollbar，title之间跳转应是平滑滚动

### ISSUE THREAD

**Issue by Ryan-yang125** [toeverything/editoe#309]
## 问题描述

 文章应该有scrollbar，title之间跳转应是平滑滚动
## 预期效果

<hr>

如果你觉得这个改进很实用、很酷，请为此 Enhancement 点个:+1:

**Comment by HeJiachen-PM** [comment]
平滑滚动无法响应长篇文章
