### ISSUE TITLE
绑定手机号后无法同步绑定微信

### ISSUE THREAD

**Issue by wenhance** [toeverything/editoe#310]
### 问题描述:用手机号注册后无法绑定微信
用手机号注册之后，无法绑定微信

### 运行环境
- 操作系统版本: 版本 1909（操作系统内部版本 18363.1443）win10家庭中文版
- 浏览器版本: 版本 89.0.774.77 (官方内部版本) (64 位) Microsoft Edge

**Comment by niudai** [comment]
直接用微信登陆，然后自动会跳转至绑定手机号

**Comment by niudai** [comment]
手机号的内容会自动同步到微信账号，两个账号会合并
