### ISSUE TITLE
正文全选会包括标题

### ISSUE THREAD

**Issue by Gurnerc** [toeverything/editoe#311]
<img width="1128" alt="截屏2021-04-20 04 18 20" src="https://user-images.githubusercontent.com/42162826/115298095-978e1b00-a18f-11eb-855a-738b3316b431.png">

运行环境
操作系统版本: 版本 Mac OS Big Sur（操作系统内部版本 11.2.3）Mac M1
浏览器版本: 版本 89.0.774.77 (官方内部版本) (64 位) Microsoft Edge

**Comment by L-Sun** [comment]
这个属于正常现象
