### ISSUE TITLE
编辑器绘图Bug反馈

### ISSUE THREAD

**Issue by MaggieHey** [toeverything/editoe#315]
### 问题描述

编辑器当前绘图功能，同一文档仅支持绘制一幅图。当绘制第二幅图保存后，文档页面未出现新绘制的图，仍为第一幅图。
### 运行环境
- 操作系统版本:  Windows 1909(操作系统内部版本 18363.1500)
- 浏览器版本:Edge 89.0.774.75

## 复现步骤:

1. 
![image](https://user-images.githubusercontent.com/65945007/115571383-83fac580-a2f1-11eb-84b1-d45abe353275.png)
绘制第一张图
2.
![image](https://user-images.githubusercontent.com/65945007/115571559-b1477380-a2f1-11eb-8322-e8387f0d9212.png)
绘制第二张图，保存
3.
![image](https://user-images.githubusercontent.com/65945007/115571607-bdcbcc00-a2f1-11eb-92b8-acc694665796.png)
第二张图保存后返回文档编辑页面，但第二张图并未出现

### 预期效果:

第二张图绘制-保存-返回 文档编辑页面后，出现在文档中

**Comment by niudai** [comment]
绘图的时候要先选中一个地方再点击绘图按钮鸭~ 那样就会插入一个新图~
