### ISSUE TITLE
复制粘贴出现白屏现象

### ISSUE THREAD

**Issue by Gurnerc** [toeverything/editoe#316]
### 问题描述
<复制粘贴出现白屏现象>

### 运行环境
- 操作系统版本: MCAOS Big Sur 11.2.3 （M1 2020）
- 浏览器版本:Microsoft Edge版本 90.0.818.42 (官方内部版本) (64 位)

## 复现步骤:
<img width="1168" alt="截屏2021-04-22 02 02 41" src="https://user-images.githubusercontent.com/42162826/115600424-473dc700-a30f-11eb-8ef6-664798425bb2.png">
1. 从其他文档中复制粘贴文字会出现白屏现象（同一篇文档，相同段落复制粘贴成功过一次，第二次再复制粘贴就白屏了）
2. 但是可以手动输入文字

**Comment by HeJiachen-PM** [comment]
应该是复制原文中带有占位符
