### ISSUE TITLE
微信有用户出现绑定两次手机，导致数据丢失

### ISSUE THREAD

**Issue by fangyuan-zheng** [toeverything/editoe#317]
### 问题描述
![image](https://user-images.githubusercontent.com/79300990/115649924-d2907a00-a35a-11eb-812a-b0b347a17bd6.png)
![image](https://user-images.githubusercontent.com/79300990/115649936-dc19e200-a35a-11eb-8c87-d1ce1e95805b.png)

### 运行环境
- 操作系统版本: 
- 浏览器版本:

## 复现步骤:

1. 
2.

**Comment by niudai** [comment]
这个应该解决了
