### ISSUE TITLE
邀请码注册，超过三个人使用会报“登录失败”

### ISSUE THREAD

**Issue by fangyuan-zheng** [toeverything/editoe#318]
### 问题描述
![image](https://user-images.githubusercontent.com/79300990/115694771-c248c100-a393-11eb-9e25-f97ef87136d2.png)

### 运行环境
- 操作系统版本: 
- 浏览器版本:

## 复现步骤:

1. 
2.

**Comment by fangyuan-zheng** [comment]
![image](https://user-images.githubusercontent.com/79300990/115811381-2ade7f00-a422-11eb-898d-16debb04fb28.png)

**Comment by byronwwang** [comment]
注册不了，收不到验证码。

**Comment by HeJiachen-PM** [comment]
邀请码已经下线
