### ISSUE TITLE
输入中文的时候有时候要反应两三秒才能打上去

### ISSUE THREAD

**Issue by jgrfg** [toeverything/editoe#324]
### 问题描述

包括按删除键的时候
### 运行环境
- 操作系统版本: WIN10
- 浏览器版本:Google Chrome 89.0.4389.128（正式版本） （64 位）

## 复现步骤:

1. 
2.

**Comment by L-Sun** [comment]
目前暂时无法复现，如果刷新页面后问题还存在，如果不介意的话，请将文档的链接发至邮箱 [zover.v@gmail.com](mailto://zover.v@gmail.com)
