### ISSUE TITLE
微信扫码登录后白屏

### ISSUE THREAD

**Issue by Megrax** [toeverything/editoe#330]
### 问题描述

尝试使用微信登录时，微信扫码确认后网页没有反应，持续白屏，刷新也没用。

还是说是因为没有开放公测所以登录不了嘛  🤣🤣  那建议也写个失败的提示叭哈哈哈哈哈  ////
### 运行环境
- 操作系统版本: MacOS Catalina 10.15.7 (19H15)
- 浏览器版本: 
    - Safari 版本14.0 (15610.1.28.1.9, 15610)
    - Google Chrome 版本 90.0.4430.212（正式版本） (x86_64)

## 复现步骤:

1. 进入 https://editoe.com 主页后点击右上角登录
2. 选择使用微信登录
3. 微信扫码后点击确认
4. 网页就变成白屏了

### 预期效果:

登录成功或者登录失败的提示？
### 实际效果:
白屏，如图：

<img width="600" alt="image" src="https://user-images.githubusercontent.com/56376387/118627409-46109480-b7fe-11eb-93e9-d9aaee681dab.png"><img width="600" alt="image" src="https://user-images.githubusercontent.com/56376387/118627797-9ab40f80-b7fe-11eb-9f34-24cb398d6e9d.png">

**Comment by Raymond-Hear** [comment]
我也遇到了这样的问题，而且手机一直收不到验证码，导致我想注册体验也体验不了

## 运行环境
- 操作系统版本: Windows 10 专业版 19042.985 (20H2)
- 浏览器版本: Microsoft Edge 版本 90.0.818.62 (官方内部版本) (64 位)

**Comment by yufish** [comment]
呵呵，广告做大发了，服务器却挂了~~~~~~~~~~
