### ISSUE TITLE
LaTeX公式无法正确显示

### ISSUE THREAD

**Issue by jjx323** [toeverything/editoe#332]
### 问题描述

如下公式代码无法正确显示
\begin{align}
\begin{split}
\nabla\cdot(\exp(u(x))\nabla w(x)) & = f(x), \quad x\in\Omega \\
w(x) & = g(x), \quad x\in\partial\Omega 
\end{split}
\end{align}

### 运行环境
- 操作系统版本:  Windows 10
- 浏览器版本: Firfox

## 复现步骤:

1. 
2. 

### 预期效果:

![image](https://user-images.githubusercontent.com/25651907/119245886-423e9280-bbaf-11eb-97e9-56e9e480964e.png)

### 实际效果:
![image](https://user-images.githubusercontent.com/25651907/119245890-4e2a5480-bbaf-11eb-8e82-fb995ebbcde4.png)

**Comment by HeJiachen-PM** [comment]
当前Katex对align环境支持不佳。本issue将在0.7中得到部分修复。

**Comment by HeJiachen-PM** [comment]
新版本对Katex升级后已支持split与align环境。
此外，行三中latex换行符应为“\\”而不是“\”。源代码改为
\begin{align}
\begin{split}
\nabla\cdot(\exp(u(x))\nabla w(x)) &= f(x), \quad x\in\Omega \\
w(x) & = g(x), \quad x\in\partial\Omega
\end{split}
\end{align}
后已正常显示：
![image](https://user-images.githubusercontent.com/79301703/141655424-bdffc3c0-e47e-4460-9375-e7f4913b766c.png)
