### ISSUE TITLE
[Enhancement]: 登录时无验证码发送【bug?】，应60秒重发验证码

### ISSUE THREAD

**Issue by StevenJokess** [toeverything/editoe#333]
## 问题描述

![image](https://user-images.githubusercontent.com/71307974/119266157-40f77f00-bc1c-11eb-972e-1578b8f5af69.png)

## 预期效果

常见的60秒重发验证码

<hr>

如果你觉得这个改进很实用、很酷，请为此 Enhancement 点个:+1:

**Comment by HeJiachen-PM** [comment]
实现这个功能需要更换云服务商。 投光 贺嘉琛

**Comment by StevenJokess** [comment]
你试下我昨天反正收不到验证码 @HeJiachen-PM

**Comment by HeJiachen-PM** [comment]
已修复
