### ISSUE TITLE
邀请码只能注册的时候用？

### ISSUE THREAD

**Issue by StevenJokess** [toeverything/editoe#334]
### 问题描述

![image](https://user-images.githubusercontent.com/71307974/119523931-c3647800-bdaf-11eb-9f73-560252e53da2.png)

对于已经注册的用户，是不能填内测码了？
### 运行环境
- 操作系统版本: 
- 浏览器版本:

## 复现步骤:

1. 找一个已经注册但没用内测码的用户，填写内测码登录
2. 

### 预期效果:

应该内测码对任何想要帮助内测的用户都可用。

**Comment by HeJiachen-PM** [comment]
已无需使用邀请码
