### ISSUE TITLE
右侧文献&文件tool拉到最左以后无法拉回去

### ISSUE THREAD

**Issue by HeJiachen-PM** [toeverything/editoe#38]
- 操作系统版本: macOS catalina
- 浏览器版本: edge chromium

复现步骤:

![image](https://user-images.githubusercontent.com/79301703/108688384-ce023d80-7532-11eb-9b6b-7fd04d86cdfa.png)

1.点开右侧tool
2.拉到最左直到与浏览器边界重合

**Comment by L-Sun** [comment]
已加入最大宽度
