### ISSUE TITLE
左侧目录栏隐藏按钮过于不显眼

### ISSUE THREAD

**Issue by HeJiachen-PM** [toeverything/editoe#39]
- 操作系统版本: macOS catalina
- 浏览器版本: edge chromium

复现步骤:

![image](https://user-images.githubusercontent.com/79301703/108688560-04d85380-7533-11eb-85bc-4e648f72ce57.png)

1.移动鼠标至左侧目录边缘以查找收缩按钮
2.收缩按钮太不显眼，也许可以加一个黑线或者与右侧样式一致

**Comment by L-Sun** [comment]
已改进！
