### ISSUE TITLE
全局页面滑动问题

### ISSUE THREAD

**Issue by Gurnerc** [toeverything/editoe#44]
- 操作系统版本: Win 10
- 浏览器版本: Chrome 88.0.4324.182（正式版本） （64 位）

复现步骤:
1.图示区域容易让用户误触改变交互插图大小or出现无法滑动页面的问题

![3b1c3ae0-159b-4b5f-abdb-487fd91973bb](https://user-images.githubusercontent.com/42162826/108783434-64e7ed80-7565-11eb-9ce4-6232f4f909f8.png)
可以采用不同的区块颜色，让用户不会发生误触，以免影响用户体验

**Comment by L-Sun** [comment]
@niudai 这个能否点击插图，才能进行鼠标交互？

**Comment by niudai** [comment]
我看看

**Comment by L-Sun** [comment]
可滚动范围已经扩大
