### ISSUE TITLE
显示页面清晰度问题

### ISSUE THREAD

**Issue by Gurnerc** [toeverything/editoe#45]
- 操作系统版本: Win 10
- 浏览器版本: Chrome 88.0.4324.182（正式版本） （64 位）

复现步骤:

1.主页面，介绍页面，图片与文字清晰度有较大差距
2. 底部的logo显示效果不是很好，可以替换

![image](https://user-images.githubusercontent.com/42162826/108783944-39b1ce00-7566-11eb-8555-33af0ba0f111.png)

![image](https://user-images.githubusercontent.com/42162826/108783968-40d8dc00-7566-11eb-96d7-ce49b1ca6657.png)

![image](https://user-images.githubusercontent.com/42162826/108784084-7aa9e280-7566-11eb-9c5a-e57197ed80c5.png)

**Comment by fangyuan-zheng** [comment]
底部logo已调整样图标式
![image](https://user-images.githubusercontent.com/79300990/108811425-3b23da80-75e8-11eb-8fd3-a6de6d8a603f.png)
