### ISSUE TITLE
黑边问题

### ISSUE THREAD

**Issue by Gurnerc** [toeverything/editoe#46]
- 操作系统版本: Win 10
- 浏览器版本: Chrome 88.0.4324.182（正式版本） （64 位）

复现步骤:
1.点击登录按钮，单机×，会出现黑边，长按会一直保持黑边

![image](https://user-images.githubusercontent.com/42162826/108784183-b80e7000-7566-11eb-8a60-8aa5de1f0038.png)

**Comment by L-Sun** [comment]
登录这个UI后面会改，之后可能就没有这个问题了

**Comment by L-Sun** [comment]
已修复
