### ISSUE TITLE
文字更改工具

### ISSUE THREAD

**Issue by Gurnerc** [toeverything/editoe#48]
- 操作系统版本: Win10
- 浏览器版本: Chrome88.0.4324.182（正式版本） （64 位）

复现步骤:
1.输入文字，工具栏，调整字体工具，这2个是一样的功能，不知道是不是bug
2.

![image](https://user-images.githubusercontent.com/42162826/108784407-3cf98980-7567-11eb-8255-846b8a760de2.png)

![image](https://user-images.githubusercontent.com/42162826/108784413-4256d400-7567-11eb-85c5-1b6731532605.png)

**Comment by L-Sun** [comment]
@Gurnerc 一个是字体颜色、一个是字体的背景颜色（类似Mark笔）

**Comment by L-Sun** [comment]
已再调色板的顶端加入提示
