### ISSUE TITLE
代码块初始状态部分情况下无法更换语言

### ISSUE THREAD

**Issue by miuer970612-24** [toeverything/editoe#5]
- 操作系统版本: win10
- 浏览器版本: chrome

复现步骤:
登录后-toolbar-插入代码块

1.如图，语言名称与对应图片重叠，导致无法选中该名称进行更换
![Lark20210219-143405](https://user-images.githubusercontent.com/79300922/108467136-b0796d80-72bf-11eb-81a0-6431cf95cde2.png)

**Comment by chenyang9725** [comment]
该问题是代码块高度太小，以至于图标和文本重叠，现给codeblock添加了最小高度。
