### ISSUE TITLE
链接转换后本文颜色没变化

### ISSUE THREAD

**Issue by niudai** [toeverything/editoe#50]
- 操作系统版本: win10
- 浏览器版本: edge

复现步骤:

链接不再自带蓝色，我记得以前链接被识别转化后是有颜色的，是啥 css 改了影响的吗？
![image](https://user-images.githubusercontent.com/44165182/108795459-8676c280-75c1-11eb-8922-b98536ca3f3b.png)

1.
2.

**Comment by L-Sun** [comment]
在迁移到next.js后变化，需要改一下netx.js的css
