### ISSUE TITLE
移动端预览文档显示问题

### ISSUE THREAD

**Issue by niudai** [toeverything/editoe#54]
- 操作系统版本:  win10
- 浏览器版本:  edge

![image](https://user-images.githubusercontent.com/44165182/108808468-ae761e00-75e1-11eb-808d-0b97d40a74d0.png)

复现步骤:

 手机进入这个 [Image](https://canary.editoe.com/docs/docb59dd640a44e1ee)

目前移动端仍然有阅读的需求，需要保证移动端的纯阅读有较好的显示效果。

现在的 title 因为宽度问题挤在一起，左边的 logo 太长，移动端希望只显示一个 logo，放在最左边，投光 the theory of everything 这个去掉，就和 favicon 那个用一个图标就行。

还有就是移动端现在默认隐藏了 toolbar，但是那个展开的 handle 仍然遮盖了一小部分内容空间，图中可以看到。

**Comment by fangyuan-zheng** [comment]
移动端的话也需要添加工具条吗？这样看起来不太好看
![image](https://user-images.githubusercontent.com/79300990/108812282-d10c3500-75e9-11eb-92ea-7855a389d8ec.png)
