### ISSUE TITLE
登录问题和文档丢失

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#56]
- 操作系统版本:Win10 
- 浏览器版本: Edge 火狐

这是几个互相关联的问题：

1.在使用手机号登录之后**马上登出**，再次登录时输入手机号后无法进行到下一步，或者虽然可以进行到下一步（即接收验证码），但实际没收到验证码，且使用之前的验证码也无法进行到下一步，登录窗口会卡死。如果第一次尝试没有遇到这样的问题，一般会在第二第三次登录时出现。
2.之前新春bug里提到过，微信扫码之后登出，会无法再登入，扫码后投光扫码页和微信系统显示为登陆成功，但实际没有。

问题1清除浏览器缓存后**有时**会解决，问题2**完全无法**靠清除缓存解决。

3.看到这里你可能会想问，这问题没意义啊，有多少人会登入后马上登出？有多少人会反复登录？我之所以会这样是因为我昨天写的文档**和**参考**彻底丢失了**（微信扫码登陆），怀疑是多次重复登录的缘故。一两次重复登录似乎没问题，但经测试半小时，重复登录大约5-6次后，我新写的文档又丢失了（这次是手机号登录）。
丢失效果：在保存原来链接的情况下打不开原来的链接，在“我的文档”中也没有痕迹

4.由3引发的疑问，手机号（注册微信的手机号）和微信扫码登录的是一个账号吗？

**Comment by niudai** [comment]
1. 手机号登陆的问题是不能在一分钟内连续发两次验证码，但是前端没有提示，这个需要修复，如果收到 repeat 应该提示等会儿再发。

**Comment by niudai** [comment]
微信登陆和手机号登陆，登陆的不是同一个账号，关于这个我们需要开发个绑定账号的功能，把两个账号的内容合并。

**Comment by niudai** [comment]
文档丢失这个应该是你使用的问题，请确保 canary 和 editoe 没混用，手机登录/微信登陆 没混用

**Comment by unknownuser1-1** [comment]
> 
> 
> 文档丢失这个应该是你使用的问题，请确保 canary 和 editoe 没混用，手机登录/微信登陆 没混用

这个我能确定没混用

**Comment by wangyu654** [comment]
> 微信登陆和手机号登陆，登陆的不是同一个账号，关于这个我们需要开发个绑定账号的功能，把两个账号的内容合并。

这个现在需要开发吗
