### ISSUE TITLE
我的文档内容显示问题

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#57]
现在点开“我的文档”之后显示页面如图

![图片](https://user-images.githubusercontent.com/79503478/108825575-2b16f580-75fe-11eb-92e5-d8e7c9233247.png)

和我的文献显示效果是完全一样的（如下图），但是我的文献很明显不在“我的文档里”，所以：
1.这个入口能否添加到“我的文档”，其实我觉得这样管理起来挺方便的
2.或者，在别的地方（最好醒目一些的地方，如和“我的文档”并列？）做入口，不然每次管理文献都得打开一篇文档才行，做用户气泡指引的时候也不方便展示，然后把界面做的不一样一些，现在连文字显示的都是“My documents”不是“My references”，不看网址真看不出区别。
![图片](https://user-images.githubusercontent.com/79503478/108825888-8cd75f80-75fe-11eb-8ae5-a40e4c348e16.png)

然后3.my documents、all files这些文字大可用中文，似乎没有什么使用英文的必要。

**Comment by niudai** [comment]
在 0.5 的规划中，sidebar 会完全接管这些功能。
