### ISSUE TITLE
分享的文档，因为链接没权限导致页面崩溃

### ISSUE THREAD

**Issue by niudai** [toeverything/editoe#60]
- 操作系统版本: 
- 浏览器版本: 

复现步骤:

请打开 [测试文档](https://canary.editoe.com/docs/doc6ca40b6c91732e96) ，页面崩溃后看报错：

（匿名状态，无法加载我的文档/文献，导致这个问题，应该尽快解决）

![image](https://user-images.githubusercontent.com/44165182/108855837-5d3b4e00-7624-11eb-8f6a-abf22d3ca64a.png)

1.
2.

**Comment by L-Sun** [comment]
相关Issue

> @L-Sun 啥意思，分享不是引用呀，为啥会涉及 two link

就是飞书的分享文章是有双向链接的，而且随人而变。如果直接显示可能会曝光用户隐私。

_Originally posted by @HeJiachen-PM in https://github.com/toeverything/editoe/issues/2#issuecomment-782590067_

**Comment by chenyang9725** [comment]
打开测试文档没有复现该问题。 需进一步明确原因

**Comment by fangyuan-zheng** [comment]
分享链接如果在未登录状态显示空白页
![image](https://user-images.githubusercontent.com/79300990/108942616-429fbe00-7692-11eb-993c-04662548074b.png)
飞书链接分享会弹出提示页面，提示点登录，登录飞书之后可以查看文档
![image](https://user-images.githubusercontent.com/79300990/108942868-b6da6180-7692-11eb-8cac-0b2163d1ca52.png)
![image](https://user-images.githubusercontent.com/79300990/108942782-96120c00-7692-11eb-896d-6bf2ca432a32.png)
@L-Sun

**Comment by L-Sun** [comment]
这个问题出现于，未登录情况下，SideWidgeList中的Timeline组件请求数据、得到null、并未对null进行判断处理。

由此引发一个问题，在未登录情况下，现在SideWidgeList中的组件都是需要登录的组件。这种情况下是否需要Disable掉SideWidgeList功能

**Comment by chenyang9725** [comment]
我建议分享的文档应有一个独立的路由，而不是和docID混用。 我们要确保每个路由独立的作用。

**Comment by L-Sun** [comment]
相关问题 #61

**Comment by chenyang9725** [comment]
> 我建议分享的文档应有一个独立的路由，而不是和docID混用。 我们要确保每个路由独立的作用。

@L-Sun 要不你来搞一下？ 路由可以为/share/[docID]

**Comment by L-Sun** [comment]
@chenyang9725 这个bug已经被修复了，现在应该不会崩溃。我再开多一个share的docID
