### ISSUE TITLE
参考文献问题集

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#65]
1. 需要一个参考文献按钮（或者其他入口，比如鼠标右键菜单中？），而非仅能由@唤出，因为不可能期望所有用户知道是要@唤出（虽然新手引导里有相关指引，但最重要的一个功能没有任何按钮，总归感觉有些奇怪，如果评估暂时不需要那就算了）
2. 参考文献各个参数之间没有分隔的标点，如何实现见飞书https://v89sa2wwaq.feishu.cn/docs/doccniLEmiZ9bLPs4221oCPZBAe
3. 参考文献格式也需按上述文档校对
3.1下图只是一个最严重的错误示例，实际还存在其他很多问题。下图中的日期在填写时填写的是2019，但会被变成01-01-2019，这里需要按之前的要求更改：日期为强制项，但不强制格式，填什么显示的就是什么，填2019，显示就是2019。在强制格式的地方，如date，则要求为年-月-日，而非不符合中文用户习惯的月-日-年。
![image](https://user-images.githubusercontent.com/79503478/112806634-95adcc00-90a9-11eb-9f9f-0d3e12026737.png)
4. 引用同一参考文献的不同页码（现在应该是必须新建一个文献）也可能需按上述文档修改，不过这个感觉技术上会很复杂，不行的话就放入0.6
5. 参考文献类别选择功能完全不能用，现在只能显示“文章”
6. 各个类别的参考文献参数并没有按需求文档实现，且实际上很多参数并不能显示，文档见飞书：https://v89sa2wwaq.feishu.cn/docs/doccnmKl6HPYN7hsTpPqyXvLyub
7. 需要能够修改、删除参考文献
8. 引用同一参考文献，正文有编号，但文末的参考文献章节中无编号
9. 重复引用一个参考文献，正文产生的编号并不相同，建议采用一个编号，这涉及到问题4的解决。

以下是在下文和后续讨论中要放入0.6版本的功能：
上文的问题1、4、7
10. 现在输入参考文献是和正文平齐（见图），物理学领域虽然有很多是如此操作，但我接触的所有文科学术论文，以及生物学领域的论文，**全部**采用上角标，希望能提供将参考文献位置改为上角标的办法。转换角标的功能本来预计在“用户设置”里实现，或者也可以考虑加一个转换按钮。
11. 鼠标悬浮在正文的参考文献角标上后，能够以浮窗显示具体的参考文献。

![image](https://user-images.githubusercontent.com/79503478/112808869-035af780-90ac-11eb-8126-aad5239c688d.png)

**Comment by HeJiachen-PM** [comment]
以及圆括号

**Comment by chenyang9725** [comment]
这种简单且需要统一的样式，也需要让用户手动更改吗？

**Comment by niudai1998** [comment]
我也觉得没必要 configurable，这种东西遵照一种规范来就行，到时候我们的编辑器和主站联动的时候，有的人用的圆括号，有的人用的上标，这什么玩意儿

**Comment by unknownuser1-1** [comment]
> 
> 
> 这种简单且需要统一的样式，也需要让用户手动更改吗？

主要是文理科差别过大，我觉得解决办法是这样：
1.需要有个用户设置，在注册时选择参考文献格式（不光是上角标，可能还涉及到具体的参考文献格式，比方说芝加哥，APA）之类，以后其系统默认就这样显示，除非他在用户设置内再次更改
2.工具栏中也需要有这么一个选项，以方便用户处理个别文献格式

**Comment by unknownuser1-1** [comment]
> 
> 我也觉得没必要 configurable，这种东西遵照一种规范来就行，到时候我们的编辑器和主站联动的时候，有的人用的圆括号，有的人用的上标，这什么玩意儿

文理科差别过大，坦白来说，文科生根本就不会用到现在这种直接跟在文字后面的参考格式，这种现实方法只会让他们觉得不正规，可能反过来也是这样，这种我觉得还是需要处理的，方法见上。
至于和主站联动，感觉上述方法也能解决？

**Comment by niudai1998** [comment]
堆到 0.6 todo list 中

**Comment by unknownuser1-1** [comment]
> 
> 堆到 0.6 todo list 中

问题2放进去，问题1应该容易解决？

**Comment by niudai1998** [comment]
对，问题 1 交给陈洋

**Comment by chenyang9725** [comment]
> > 堆到 0.6 todo list 中
> 
> 问题2放进去，问题1（就是参考文献按钮）应该容易解决？

嗯

**Comment by chenyang9725** [comment]
@wangyu654  @fangyuan-zheng 
应产品需求，文献录入的日期选项可以填汉字如(汉朝), 王宇你看看怎么改。
然后timeline就只按年份排序，同一年内的文献不分顺序，没有日期或日期不明确的如(汉朝),放到未分组里。

**Comment by fangyuan-zheng** [comment]
tinline排序已改

**Comment by unknownuser1-1** [comment]
全部整合至跟踪文档
