### ISSUE TITLE
恢复被系统删除的问题（二） 顶部工具栏问题

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#66]
- 操作系统版本: win10
- 浏览器版本: edge

1. 顶部工具栏隐藏后无法唤出，上回孙豪文发现是“展开按钮位于左上角、且变为透明”。
2. 顶部工具栏左侧顶格，右侧却不是，反而在文档编辑区右侧边换行，需要统一。

**Comment by L-Sun** [comment]
@chenyang9725 工具栏的展开收缩按钮是不是应该一直是显示的、不需要隐藏，我一开始也以为是bug消失掉了。

**Comment by miuer970612-24** [comment]
@L-Sun 目前是工具栏收起后，鼠标移至左上角显示展开符号；这样确实不太明确，可以改成一直显示，或者增加鼠标感应范围

**Comment by chenyang9725** [comment]
现在隐藏toolbar后， 指示按钮将一直在左上角显示
