### ISSUE TITLE
Mac 带斜杠的请求发生 redirect 后 authorization 的 header 会去掉导致请求失败返回 401

### ISSUE THREAD

**Issue by niudai** [toeverything/editoe#67]
- 操作系统版本:  11.1
- 浏览器版本:  Safari

如题

复现步骤:

1.
2.

**Comment by niudai** [comment]
Safari 只会忽略 Authorization 的 header，只需换一个名字即可。
有一个简单的解决方案，需要前后端同时协作。
后端先同时兼容 Authorization 和 X-Authorization 两个 header，这样前端未更新和更新后都能正常工作，然后前端把 header 换成 X-Authorization  @wangyu654 @fangyuan-zheng

**Comment by fangyuan-zheng** [comment]
已改
