### ISSUE TITLE
右键呼出toolbar某些情况下会被顶栏遮挡

### ISSUE THREAD

**Issue by miuer970612-24** [toeverything/editoe#68]
- 操作系统版本: win 10
- 浏览器版本: Edge

复现步骤:

![ec4dc36290e30f8bac10ec600f8a333](https://user-images.githubusercontent.com/79300922/109032470-a791fd00-7700-11eb-8382-b775d6ef1cc9.png)

**Comment by L-Sun** [comment]
已经优化，但如果窗口小于菜单时，就一定会遮挡了
