### ISSUE TITLE
顶部菜单栏问题

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#69]
1.原先修改文档标题应当是在顶部菜单栏进行，现在好像修改的地方消失了（见下图），不知道现在如何修改文章标题？
2.左侧的投光logo希望能保留文字。

![图片](https://user-images.githubusercontent.com/79503478/109094593-329ce280-7755-11eb-82ba-7b613d286130.png)

**Comment by chenyang9725** [comment]
#70 标题到时候也要移动到正文内， 所以问题1就不是问题了
问题2已解决
