### ISSUE TITLE
导出的pdf不会自动隐藏toolbar和sidebar，已勾选的待办项导出后变成未勾选状态

### ISSUE THREAD

**Issue by miuer970612-24** [toeverything/editoe#7]
- 操作系统版本: win 10
- 浏览器版本: chrome

复现步骤:登录-导出为pdf

![Lark20210219-145321](https://user-images.githubusercontent.com/79300922/108468800-3d252b00-72c2-11eb-8434-1e4356ac7af0.png)

**Comment by L-Sun** [comment]
已修复
