### ISSUE TITLE
建议文本的第一行作为标题，默认为 h1

### ISSUE THREAD

**Issue by niudai** [toeverything/editoe#70]

**Comment by niudai** [comment]
请参考飞书的实现。
目前在顶栏编辑，其实比较反用户的直觉，还是这样更合适一点。

**Comment by chenyang9725** [comment]
这个想法在当初讨论标题的时候就提出来， 由于反对就放弃了

**Comment by L-Sun** [comment]
或者是把标题放在正文上面，但不是编辑器的内容

**Comment by chenyang9725** [comment]
> 或者是把标题放在正文上面，但不是编辑器的内容。视觉上看起来是和正文一起的，其实是两个东西

之前搞过， 有点丑
