### ISSUE TITLE
编辑器亟需按钮列表

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#73]
1. 搜索、替换特定文本（参见word功能）
2.  将文字、数字（非脚注）设定为上角标、下角标，上角标不必说，下角标可能需要特定效果，如LD50中的50，不是单纯的LD`50`，而是：
![图片](https://user-images.githubusercontent.com/79503478/109113016-81a73f80-7776-11eb-9513-b1a915209d00.png)
3.字体和字体大小的按钮一样，需要重新设计一个字体按钮：
![图片](https://user-images.githubusercontent.com/79503478/109135499-1a978400-7792-11eb-81c2-78cb886c66fa.png)

**Comment by L-Sun** [comment]
图标需要做一下 @miuer970612-24

**Comment by fangyuan-zheng** [comment]
两个字体icon一样 已改

**Comment by L-Sun** [comment]
上下标问题得用数学公式
