### ISSUE TITLE
直接复制粘贴外部链接时自带文字过多

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#74]
1.例如复制粘贴另一篇投光文档时，自带文字过多，如下图中只需保留文档标题“untitled”即可，不需要后面的-Editoe。复制外部网址（如百度图片）也有类似问题。
2.但复制谷歌图片却没有自带文字，不知何故。如果外部网址没法做到统一，不如除去透光编辑器自己的链接，别的都不要自带文字了：
![图片](https://user-images.githubusercontent.com/79503478/109116428-773b7480-777b-11eb-9926-7920ff7a46ba.png)

**Comment by L-Sun** [comment]
这个属于正常的现象，链接的标题是由原网页的标题确定的。

**Comment by unknownuser1-1** [comment]
> 
> 
> 这个属于正常的现象，链接的标题是由原网页的标题确定的。

那2就算了，1我的意思是说把“-Editoe”去掉，同飞书，这个后缀没有用，删除完全是浪费用户时间。

**Comment by L-Sun** [comment]
已去掉
