### ISSUE TITLE
导出 pdf，toolbar 未隐藏

### ISSUE THREAD

**Issue by niudai** [toeverything/editoe#75]
- 操作系统版本: 11.1 (20C69)
- 浏览器版本: chrome

复现步骤:

![image](https://user-images.githubusercontent.com/44165182/109119816-24b08700-7780-11eb-92c1-128fb4b2e61d.png)

1.
2.

**Comment by chenyang9725** [comment]
这个pdf功能应该由后端来做，而不是调用浏览器api，document.print，不然每当页面有变化的时候，都需要进行相应的改动

**Comment by niudai** [comment]
嗯，我也觉得，服务端运行一个无头浏览器

**Comment by L-Sun** [comment]
问题转移至 #102
