### ISSUE TITLE
文献Timeline中创建同名文件夹，会导致页面崩溃

### ISSUE THREAD

**Issue by L-Sun** [toeverything/editoe#82]
- 操作系统版本: Win10 
- 浏览器版本: Edge

复现步骤:

文献Timeline中创建同名文件夹，如两个a文件夹
![image](https://user-images.githubusercontent.com/20479050/109264361-d82c8080-783f-11eb-9184-7a2b5c259f81.png)

**Comment by fangyuan-zheng** [comment]
已处理
