### ISSUE TITLE
图片功能bugs

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#84]
- 操作系统版本: win10
- 浏览器版本: Edge

复现步骤:
1.复制得到一张图片后，在将图片缩小到一定比例时（百分比似乎不定），会无法继续缩小，下图为18%左右（下图上面的Latex图标为11.8%左右），之后继续拖动鼠标缩小，图片不会继续变小，只有图片的caption栏位在不断缩小。且该栏位将与图片本身的栏位分离。
![图片](https://user-images.githubusercontent.com/79503478/109270816-8e489800-7849-11eb-8a1c-a9ec2d79b11e.png)
2.需要图片可以插入文字中间，原因见下文讨论
3.需要图片可以并列，现在效果是：
![图片](https://user-images.githubusercontent.com/79503478/109939321-e8df6980-7d0b-11eb-85c7-5e0f9c4e0ed4.png)

**Comment by L-Sun** [comment]
图片需要有个最小宽度才行

**Comment by unknownuser1-1** [comment]
> 
> 
> 图片需要有个最小宽度才行

是得有，不过现在这个有点太宽了，这个在原网站维基百科只是一个和文字等大的按钮

**Comment by L-Sun** [comment]
> > 图片需要有个最小宽度才行
> 
> 是得有，不过现在这个有点太宽了，这个在原网站维基百科只是一个和文字等大的按钮

对这类小图片，其实应该叫图标。个人感觉不应该以图片的方式来插入这种东西，更推荐用Emoji✏。不过目前我们好像不支持Emoji输入。

**Comment by unknownuser1-1** [comment]
> 
> 
> > > 图片需要有个最小宽度才行
> > 
> > 
> > 是得有，不过现在这个有点太宽了，这个在原网站维基百科只是一个和文字等大的按钮
> 
> 对这类小图片，其实应该叫图标。个人感觉不应该以图片的方式来插入这种东西，更推荐用Emoji✏。不过目前我们好像不支持Emoji输入。

也不是所有小图片都有emoji吧，各种公司商标之类有版权的图片也有需要缩小的时候。

**Comment by L-Sun** [comment]
这个问题所说的小图片，不应当以figure的形式，而是应该以sticker的形式，类似表情，用户可以自定义这类sticker，并可以在文章内输入。
