### ISSUE TITLE
首页显示问题

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#85]
1. 首页底部缺乏版权标记，见下图飞书底部标记
![图片](https://user-images.githubusercontent.com/79503478/109278470-88f04b00-7853-11eb-8259-03e5ae371831.png)

2. 右上角菜单在某些时候会和内文文字重叠，不太优雅（见下图），需要使二者不冲突，比如在重叠时将页面上内容做一定的虚化，或者如飞书一样将菜单栏完全不透明化（下下图）。
![图片](https://user-images.githubusercontent.com/79503478/109278612-ac1afa80-7853-11eb-82ed-6c912aa4a022.png)
![图片](https://user-images.githubusercontent.com/79503478/109278786-e7b5c480-7853-11eb-8fab-f17fc1a085bd.png)

**Comment by L-Sun** [comment]
@fangyuan-zheng 弄个向下滚动的时候，隐藏右上角的菜单栏；向上滚动时就显示菜单栏，并加上个背景或虚化等。

**Comment by fangyuan-zheng** [comment]
已解决
