### ISSUE TITLE
参考文献日期

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#89]
上周周会我记得讨论过参考文献日期部分不再强制填写日月年，“日期”将来还是个强制参数，但是不强制日月年，可以自由填写这意思，现在好像没撤掉这功能。
![图片](https://user-images.githubusercontent.com/79503478/109450523-11563200-7a86-11eb-8cc3-5398d26e08d3.png)

**Comment by chenyang9725** [comment]
只是Bibtex的限制放宽了， 表格录入的并没有， date是必须的，因为文献放在timeline里是按时间排序的

**Comment by unknownuser1-1** [comment]
> 
> 
> 只是Bibtex的限制放宽了， 表格录入的并没有， date是必须的，因为文献放在timeline里是按时间排序的

**绝大多数**学术文献和学术文献参考系统根本就没有出版月日，只有年份，甚至有些是没年份的，一般这时候学术论文要求用n.d，不能让用户来适应我们的系统吧。至于排序，可以按年份排文献，没日期的可以另外分一个地方。至于为了排序强求加入月日，肯定不可行。

**Comment by chenyang9725** [comment]
好吧，那就放宽时间的限制

**Comment by unknownuser1-1** [comment]
> 
> 
> 好吧，那就放宽时间的限制

这个如果不是特别难的话尽快改一下呗，现在写东西参考文献大部分都不能用太难受。

**Comment by chenyang9725** [comment]
![image](https://user-images.githubusercontent.com/79300514/110080256-2bb14800-7dc5-11eb-9935-7f814558f0a1.png)
现在timeline这里的文献时按照日期排序的，如果创建的文献没有日期，那么这些文献放的位置，要不要设计一下？ 还是说研发按自己的意思来

**Comment by unknownuser1-1** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/79300514/110080256-2bb14800-7dc5-11eb-9935-7f814558f0a1.png)
> 现在timeline这里的文献是按照日期排序的，如果创建的文献没有日期，那么这些文献放的位置，要不要设计一下？ 还是说研发按自己的意思来

这种完全没日期的其实也不多，我们就增加一个“无日期”的栏位（就在2016/2017这些位置），然后按加入时间排就可以了。

**Comment by chenyang9725** [comment]
@fangyuan-zheng 我来搞文献创建放宽限制，不带时间， 你处理下不带时间的文献放置的位置

**Comment by fangyuan-zheng** [comment]
ok

**Comment by fangyuan-zheng** [comment]
已改
