### ISSUE TITLE
sidebar文献笔记问题

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#90]
参考文献里的“请输入笔记”功能似乎有点bug：
1 输入内容之后点击右侧菜单栏内其他位置，还会变回之前内容。
2 似乎没办法删除内容，清空后刷新页面，还保留原来文字。
3 现在时间线上点+键还有一个输入笔记的地方，但输入后位置不同，而删除时确实也叫笔记，不知道有何区别，是不是统一成一个。
4 如果决定保留时间线上的笔记，需要将其中的英文“Input your note”汉化。
![image](https://user-images.githubusercontent.com/79503478/112942359-92c2e200-9162-11eb-984c-806e092925f4.png)

**Comment by L-Sun** [comment]
@wangyu654 更新笔记的时候，如果内容是空的话，似乎会更新失败
