### ISSUE TITLE
一个关于左上角logo链接的较严重的显示问题

### ISSUE THREAD

**Issue by unknownuser1-1** [toeverything/editoe#99]
打开一个文档，再点击左上角logo，进入首页（好像也不能ctrl+左键在新窗口打开），此时点击返回，不会返回到原来的文档页，虽然网址会变成文档的网址，但是显示的还是首页。
![图片](https://user-images.githubusercontent.com/79503478/109618084-198b9b80-7b72-11eb-8ef4-9ab060ba1a2c.png)

**Comment by L-Sun** [comment]
@fangyuan-zheng 这个需要加个a标签，其它的问题都已经修复了
